-- =====================================================================
-- C.O.G.N.I.T. Image Seed
-- Replaced with numbered SVG assets (1.svg ... 62.svg)
-- Safe to run multiple times (idempotent upserts)
-- =====================================================================

BEGIN;

INSERT INTO images (image_id, url, difficulty, object_count, width, height)
VALUES
    ('1.svg', 'https://cognitapi.s3.us-east-1.amazonaws.com/survey/1.svg', 5.0, 1, NULL, NULL),
    ('2.svg', 'https://cognitapi.s3.us-east-1.amazonaws.com/survey/2.svg', 5.0, 1, NULL, NULL),
    ('3.svg', 'https://cognitapi.s3.us-east-1.amazonaws.com/survey/3.svg', 5.0, 1, NULL, NULL),
    ('4.svg', 'https://cognitapi.s3.us-east-1.amazonaws.com/survey/4.svg', 5.0, 1, NULL, NULL),
    ('5.svg', 'https://cognitapi.s3.us-east-1.amazonaws.com/survey/5.svg', 5.0, 1, NULL, NULL),
    ('6.svg', 'https://cognitapi.s3.us-east-1.amazonaws.com/survey/6.svg', 5.0, 1, NULL, NULL),
    ('7.svg', 'https://cognitapi.s3.us-east-1.amazonaws.com/survey/7.svg', 5.0, 1, NULL, NULL),
    ('8.svg', 'https://cognitapi.s3.us-east-1.amazonaws.com/survey/8.svg', 5.0, 1, NULL, NULL),
    ('9.svg', 'https://cognitapi.s3.us-east-1.amazonaws.com/survey/9.svg', 5.0, 1, NULL, NULL),
    ('10.svg', 'https://cognitapi.s3.us-east-1.amazonaws.com/survey/10.svg', 5.0, 1, NULL, NULL),
    ('11.svg', 'https://cognitapi.s3.us-east-1.amazonaws.com/survey/11.svg', 5.0, 1, NULL, NULL),
    ('12.svg', 'https://cognitapi.s3.us-east-1.amazonaws.com/survey/12.svg', 5.0, 1, NULL, NULL),
    ('13.svg', 'https://cognitapi.s3.us-east-1.amazonaws.com/survey/13.svg', 5.0, 1, NULL, NULL),
    ('14.svg', 'https://cognitapi.s3.us-east-1.amazonaws.com/survey/14.svg', 5.0, 1, NULL, NULL),
    ('15.svg', 'https://cognitapi.s3.us-east-1.amazonaws.com/survey/15.svg', 5.0, 1, NULL, NULL),
    ('16.svg', 'https://cognitapi.s3.us-east-1.amazonaws.com/survey/16.svg', 5.0, 1, NULL, NULL),
    ('17.svg', 'https://cognitapi.s3.us-east-1.amazonaws.com/survey/17.svg', 5.0, 1, NULL, NULL),
    ('18.svg', 'https://cognitapi.s3.us-east-1.amazonaws.com/survey/18.svg', 5.0, 1, NULL, NULL),
    ('19.svg', 'https://cognitapi.s3.us-east-1.amazonaws.com/survey/19.svg', 5.0, 1, NULL, NULL),
    ('20.svg', 'https://cognitapi.s3.us-east-1.amazonaws.com/survey/20.svg', 5.0, 1, NULL, NULL),
    ('21.svg', 'https://cognitapi.s3.us-east-1.amazonaws.com/survey/21.svg', 5.0, 1, NULL, NULL),
    ('22.svg', 'https://cognitapi.s3.us-east-1.amazonaws.com/survey/22.svg', 5.0, 1, NULL, NULL),
    ('23.svg', 'https://cognitapi.s3.us-east-1.amazonaws.com/survey/23.svg', 5.0, 1, NULL, NULL),
    ('24.svg', 'https://cognitapi.s3.us-east-1.amazonaws.com/survey/24.svg', 5.0, 1, NULL, NULL),
    ('25.svg', 'https://cognitapi.s3.us-east-1.amazonaws.com/survey/25.svg', 5.0, 1, NULL, NULL),
    ('26.svg', 'https://cognitapi.s3.us-east-1.amazonaws.com/survey/26.svg', 5.0, 1, NULL, NULL),
    ('27.svg', 'https://cognitapi.s3.us-east-1.amazonaws.com/survey/27.svg', 5.0, 1, NULL, NULL),
    ('28.svg', 'https://cognitapi.s3.us-east-1.amazonaws.com/survey/28.svg', 5.0, 1, NULL, NULL),
    ('29.svg', 'https://cognitapi.s3.us-east-1.amazonaws.com/survey/29.svg', 5.0, 1, NULL, NULL),
    ('30.svg', 'https://cognitapi.s3.us-east-1.amazonaws.com/survey/30.svg', 5.0, 1, NULL, NULL),
    ('31.svg', 'https://cognitapi.s3.us-east-1.amazonaws.com/survey/31.svg', 5.0, 1, NULL, NULL),
    ('32.svg', 'https://cognitapi.s3.us-east-1.amazonaws.com/survey/32.svg', 5.0, 1, NULL, NULL),
    ('33.svg', 'https://cognitapi.s3.us-east-1.amazonaws.com/survey/33.svg', 5.0, 1, NULL, NULL),
    ('34.svg', 'https://cognitapi.s3.us-east-1.amazonaws.com/survey/34.svg', 5.0, 1, NULL, NULL),
    ('35.svg', 'https://cognitapi.s3.us-east-1.amazonaws.com/survey/35.svg', 5.0, 1, NULL, NULL),
    ('36.svg', 'https://cognitapi.s3.us-east-1.amazonaws.com/survey/36.svg', 5.0, 1, NULL, NULL),
    ('37.svg', 'https://cognitapi.s3.us-east-1.amazonaws.com/survey/37.svg', 5.0, 1, NULL, NULL),
    ('38.svg', 'https://cognitapi.s3.us-east-1.amazonaws.com/survey/38.svg', 5.0, 1, NULL, NULL),
    ('39.svg', 'https://cognitapi.s3.us-east-1.amazonaws.com/survey/39.svg', 5.0, 1, NULL, NULL),
    ('40.svg', 'https://cognitapi.s3.us-east-1.amazonaws.com/survey/40.svg', 5.0, 1, NULL, NULL),
    ('41.svg', 'https://cognitapi.s3.us-east-1.amazonaws.com/survey/41.svg', 5.0, 1, NULL, NULL),
    ('42.svg', 'https://cognitapi.s3.us-east-1.amazonaws.com/survey/42.svg', 5.0, 1, NULL, NULL),
    ('43.svg', 'https://cognitapi.s3.us-east-1.amazonaws.com/survey/43.svg', 5.0, 1, NULL, NULL),
    ('44.svg', 'https://cognitapi.s3.us-east-1.amazonaws.com/survey/44.svg', 5.0, 1, NULL, NULL),
    ('45.svg', 'https://cognitapi.s3.us-east-1.amazonaws.com/survey/45.svg', 5.0, 1, NULL, NULL),
    ('46.svg', 'https://cognitapi.s3.us-east-1.amazonaws.com/survey/46.svg', 5.0, 1, NULL, NULL),
    ('47.svg', 'https://cognitapi.s3.us-east-1.amazonaws.com/survey/47.svg', 5.0, 1, NULL, NULL),
    ('48.svg', 'https://cognitapi.s3.us-east-1.amazonaws.com/survey/48.svg', 5.0, 1, NULL, NULL),
    ('49.svg', 'https://cognitapi.s3.us-east-1.amazonaws.com/survey/49.svg', 5.0, 1, NULL, NULL),
    ('50.svg', 'https://cognitapi.s3.us-east-1.amazonaws.com/survey/50.svg', 5.0, 1, NULL, NULL),
    ('51.svg', 'https://cognitapi.s3.us-east-1.amazonaws.com/survey/51.svg', 5.0, 1, NULL, NULL),
    ('52.svg', 'https://cognitapi.s3.us-east-1.amazonaws.com/survey/52.svg', 5.0, 1, NULL, NULL),
    ('53.svg', 'https://cognitapi.s3.us-east-1.amazonaws.com/survey/53.svg', 5.0, 1, NULL, NULL),
    ('54.svg', 'https://cognitapi.s3.us-east-1.amazonaws.com/survey/54.svg', 5.0, 1, NULL, NULL),
    ('55.svg', 'https://cognitapi.s3.us-east-1.amazonaws.com/survey/55.svg', 5.0, 1, NULL, NULL),
    ('56.svg', 'https://cognitapi.s3.us-east-1.amazonaws.com/survey/56.svg', 5.0, 1, NULL, NULL),
    ('57.svg', 'https://cognitapi.s3.us-east-1.amazonaws.com/survey/57.svg', 5.0, 1, NULL, NULL),
    ('58.svg', 'https://cognitapi.s3.us-east-1.amazonaws.com/survey/58.svg', 5.0, 1, NULL, NULL),
    ('59.svg', 'https://cognitapi.s3.us-east-1.amazonaws.com/survey/59.svg', 5.0, 1, NULL, NULL),
    ('60.svg', 'https://cognitapi.s3.us-east-1.amazonaws.com/survey/60.svg', 5.0, 1, NULL, NULL),
    ('61.svg', 'https://cognitapi.s3.us-east-1.amazonaws.com/survey/61.svg', 5.0, 1, NULL, NULL),
    ('62.svg', 'https://cognitapi.s3.us-east-1.amazonaws.com/survey/62.svg', 5.0, 1, NULL, NULL)
ON CONFLICT (image_id) DO UPDATE SET
    url          = EXCLUDED.url,
    difficulty   = EXCLUDED.difficulty,
    object_count = EXCLUDED.object_count,
    width        = EXCLUDED.width,
    height       = EXCLUDED.height;

COMMIT;
