-- =====================================================
-- C.O.G.N.I.T. Images Seed Data
-- Contains AWS S3 URLs for all survey images
-- =====================================================

INSERT INTO images (image_id, s3_key, s3_url, difficulty_score, object_count, width, height, content_type) VALUES
('survey/attention-circle.svg', 'attention-circle.svg', 'https://cognitapi.s3.us-east-1.amazonaws.com/survey/attention-circle.svg', 5.0, 1, 800, 600, 'image/svg+xml'),
('survey/attention-ocean.svg', 'attention-ocean.svg', 'https://cognitapi.s3.us-east-1.amazonaws.com/survey/attention-ocean.svg', 5.0, 1, 800, 600, 'image/svg+xml'),
('survey/attention-red.svg', 'attention-red.svg', 'https://cognitapi.s3.us-east-1.amazonaws.com/survey/attention-red.svg', 5.0, 1, 800, 600, 'image/svg+xml'),
('survey/aurora-lake.svg', 'aurora-lake.svg', 'https://cognitapi.s3.us-east-1.amazonaws.com/survey/aurora-lake.svg', 5.0, 1, 800, 600, 'image/svg+xml'),
('survey/bunny-garden.svg', 'bunny-garden.svg', 'https://cognitapi.s3.us-east-1.amazonaws.com/survey/bunny-garden.svg', 5.0, 1, 800, 600, 'image/svg+xml'),
('survey/cat-play.svg', 'cat-play.svg', 'https://cognitapi.s3.us-east-1.amazonaws.com/survey/cat-play.svg', 5.0, 1, 800, 600, 'image/svg+xml'),
('survey/coral-reef.svg', 'coral-reef.svg', 'https://cognitapi.s3.us-east-1.amazonaws.com/survey/coral-reef.svg', 5.0, 1, 800, 600, 'image/svg+xml'),
('survey/cute-alpaca.svg', 'cute-alpaca.svg', 'https://cognitapi.s3.us-east-1.amazonaws.com/survey/cute-alpaca.svg', 5.0, 1, 800, 600, 'image/svg+xml'),
('survey/cute-bear.svg', 'cute-bear.svg', 'https://cognitapi.s3.us-east-1.amazonaws.com/survey/cute-bear.svg', 5.0, 1, 800, 600, 'image/svg+xml'),
('survey/cute-bunny.svg', 'cute-bunny.svg', 'https://cognitapi.s3.us-east-1.amazonaws.com/survey/cute-bunny.svg', 5.0, 1, 800, 600, 'image/svg+xml'),
('survey/cute-calf.svg', 'cute-calf.svg', 'https://cognitapi.s3.us-east-1.amazonaws.com/survey/cute-calf.svg', 5.0, 1, 800, 600, 'image/svg+xml'),
('survey/cute-chick.svg', 'cute-chick.svg', 'https://cognitapi.s3.us-east-1.amazonaws.com/survey/cute-chick.svg', 5.0, 1, 800, 600, 'image/svg+xml'),
('survey/cute-deer.svg', 'cute-deer.svg', 'https://cognitapi.s3.us-east-1.amazonaws.com/survey/cute-deer.svg', 5.0, 1, 800, 600, 'image/svg+xml'),
('survey/cute-dolphin.svg', 'cute-dolphin.svg', 'https://cognitapi.s3.us-east-1.amazonaws.com/survey/cute-dolphin.svg', 5.0, 1, 800, 600, 'image/svg+xml'),
('survey/cute-duck.svg', 'cute-duck.svg', 'https://cognitapi.s3.us-east-1.amazonaws.com/survey/cute-duck.svg', 5.0, 1, 800, 600, 'image/svg+xml'),
('survey/cute-elephant.svg', 'cute-elephant.svg', 'https://cognitapi.s3.us-east-1.amazonaws.com/survey/cute-elephant.svg', 5.0, 1, 800, 600, 'image/svg+xml'),
('survey/cute-fox.svg', 'cute-fox.svg', 'https://cognitapi.s3.us-east-1.amazonaws.com/survey/cute-fox.svg', 5.0, 1, 800, 600, 'image/svg+xml'),
('survey/cute-frog.svg', 'cute-frog.svg', 'https://cognitapi.s3.us-east-1.amazonaws.com/survey/cute-frog.svg', 5.0, 1, 800, 600, 'image/svg+xml'),
('survey/cute-giraffe.svg', 'cute-giraffe.svg', 'https://cognitapi.s3.us-east-1.amazonaws.com/survey/cute-giraffe.svg', 5.0, 1, 800, 600, 'image/svg+xml'),
('survey/cute-hedgehog.svg', 'cute-hedgehog.svg', 'https://cognitapi.s3.us-east-1.amazonaws.com/survey/cute-hedgehog.svg', 5.0, 1, 800, 600, 'image/svg+xml'),
('survey/cute-kitten.svg', 'cute-kitten.svg', 'https://cognitapi.s3.us-east-1.amazonaws.com/survey/cute-kitten.svg', 5.0, 1, 800, 600, 'image/svg+xml'),
('survey/cute-koala.svg', 'cute-koala.svg', 'https://cognitapi.s3.us-east-1.amazonaws.com/survey/cute-koala.svg', 5.0, 1, 800, 600, 'image/svg+xml'),
('survey/cute-lamb.svg', 'cute-lamb.svg', 'https://cognitapi.s3.us-east-1.amazonaws.com/survey/cute-lamb.svg', 5.0, 1, 800, 600, 'image/svg+xml'),
('survey/cute-lion.svg', 'cute-lion.svg', 'https://cognitapi.s3.us-east-1.amazonaws.com/survey/cute-lion.svg', 5.0, 1, 800, 600, 'image/svg+xml'),
('survey/cute-otter.svg', 'cute-otter.svg', 'https://cognitapi.s3.us-east-1.amazonaws.com/survey/cute-otter.svg', 5.0, 1, 800, 600, 'image/svg+xml'),
('survey/cute-owl.svg', 'cute-owl.svg', 'https://cognitapi.s3.us-east-1.amazonaws.com/survey/cute-owl.svg', 5.0, 1, 800, 600, 'image/svg+xml'),
('survey/cute-panda.svg', 'cute-panda.svg', 'https://cognitapi.s3.us-east-1.amazonaws.com/survey/cute-panda.svg', 5.0, 1, 800, 600, 'image/svg+xml'),
('survey/cute-penguin.svg', 'cute-penguin.svg', 'https://cognitapi.s3.us-east-1.amazonaws.com/survey/cute-penguin.svg', 5.0, 1, 800, 600, 'image/svg+xml'),
('survey/cute-piglet.svg', 'cute-piglet.svg', 'https://cognitapi.s3.us-east-1.amazonaws.com/survey/cute-piglet.svg', 5.0, 1, 800, 600, 'image/svg+xml'),
('survey/cute-puppy.svg', 'cute-puppy.svg', 'https://cognitapi.s3.us-east-1.amazonaws.com/survey/cute-puppy.svg', 5.0, 1, 800, 600, 'image/svg+xml'),
('survey/cute-raccoon.svg', 'cute-raccoon.svg', 'https://cognitapi.s3.us-east-1.amazonaws.com/survey/cute-raccoon.svg', 5.0, 1, 800, 600, 'image/svg+xml'),
('survey/cute-seal.svg', 'cute-seal.svg', 'https://cognitapi.s3.us-east-1.amazonaws.com/survey/cute-seal.svg', 5.0, 1, 800, 600, 'image/svg+xml'),
('survey/cute-sloth.svg', 'cute-sloth.svg', 'https://cognitapi.s3.us-east-1.amazonaws.com/survey/cute-sloth.svg', 5.0, 1, 800, 600, 'image/svg+xml'),
('survey/cute-squirrel.svg', 'cute-squirrel.svg', 'https://cognitapi.s3.us-east-1.amazonaws.com/survey/cute-squirrel.svg', 5.0, 1, 800, 600, 'image/svg+xml'),
('survey/cute-tiger.svg', 'cute-tiger.svg', 'https://cognitapi.s3.us-east-1.amazonaws.com/survey/cute-tiger.svg', 5.0, 1, 800, 600, 'image/svg+xml'),
('survey/cute-turtle.svg', 'cute-turtle.svg', 'https://cognitapi.s3.us-east-1.amazonaws.com/survey/cute-turtle.svg', 5.0, 1, 800, 600, 'image/svg+xml'),
('survey/cute-unicorn.svg', 'cute-unicorn.svg', 'https://cognitapi.s3.us-east-1.amazonaws.com/survey/cute-unicorn.svg', 5.0, 1, 800, 600, 'image/svg+xml'),
('survey/desert-dunes.svg', 'desert-dunes.svg', 'https://cognitapi.s3.us-east-1.amazonaws.com/survey/desert-dunes.svg', 5.0, 1, 800, 600, 'image/svg+xml'),
('survey/dog-sunny.svg', 'dog-sunny.svg', 'https://cognitapi.s3.us-east-1.amazonaws.com/survey/dog-sunny.svg', 5.0, 1, 800, 600, 'image/svg+xml'),
('survey/forest-stream.svg', 'forest-stream.svg', 'https://cognitapi.s3.us-east-1.amazonaws.com/survey/forest-stream.svg', 5.0, 1, 800, 600, 'image/svg+xml'),
('survey/fox-cloud.svg', 'fox-cloud.svg', 'https://cognitapi.s3.us-east-1.amazonaws.com/survey/fox-cloud.svg', 5.0, 1, 800, 600, 'image/svg+xml'),
('survey/glacier-bay.svg', 'glacier-bay.svg', 'https://cognitapi.s3.us-east-1.amazonaws.com/survey/glacier-bay.svg', 5.0, 1, 800, 600, 'image/svg+xml'),
('survey/golden-temple.svg', 'golden-temple.svg', 'https://cognitapi.s3.us-east-1.amazonaws.com/survey/golden-temple.svg', 5.0, 1, 800, 600, 'image/svg+xml'),
('survey/hamster-wheel.svg', 'hamster-wheel.svg', 'https://cognitapi.s3.us-east-1.amazonaws.com/survey/hamster-wheel.svg', 5.0, 1, 800, 600, 'image/svg+xml'),
('survey/harbor-dawn.svg', 'harbor-dawn.svg', 'https://cognitapi.s3.us-east-1.amazonaws.com/survey/harbor-dawn.svg', 5.0, 1, 800, 600, 'image/svg+xml'),
('survey/kitten-yarn.svg', 'kitten-yarn.svg', 'https://cognitapi.s3.us-east-1.amazonaws.com/survey/kitten-yarn.svg', 5.0, 1, 800, 600, 'image/svg+xml'),
('survey/lavender-fields.svg', 'lavender-fields.svg', 'https://cognitapi.s3.us-east-1.amazonaws.com/survey/lavender-fields.svg', 5.0, 1, 800, 600, 'image/svg+xml'),
('survey/midnight-city.svg', 'midnight-city.svg', 'https://cognitapi.s3.us-east-1.amazonaws.com/survey/midnight-city.svg', 5.0, 1, 800, 600, 'image/svg+xml'),
('survey/misty-valley.svg', 'misty-valley.svg', 'https://cognitapi.s3.us-east-1.amazonaws.com/survey/misty-valley.svg', 5.0, 1, 800, 600, 'image/svg+xml'),
('survey/moonlit-meadow.svg', 'moonlit-meadow.svg', 'https://cognitapi.s3.us-east-1.amazonaws.com/survey/moonlit-meadow.svg', 5.0, 1, 800, 600, 'image/svg+xml'),
('survey/northern-peaks.svg', 'northern-peaks.svg', 'https://cognitapi.s3.us-east-1.amazonaws.com/survey/northern-peaks.svg', 5.0, 1, 800, 600, 'image/svg+xml'),
('survey/orchid-garden.svg', 'orchid-garden.svg', 'https://cognitapi.s3.us-east-1.amazonaws.com/survey/orchid-garden.svg', 5.0, 1, 800, 600, 'image/svg+xml'),
('survey/puppy-ball.svg', 'puppy-ball.svg', 'https://cognitapi.s3.us-east-1.amazonaws.com/survey/puppy-ball.svg', 5.0, 1, 800, 600, 'image/svg+xml'),
('survey/rainbow-cliff.svg', 'rainbow-cliff.svg', 'https://cognitapi.s3.us-east-1.amazonaws.com/survey/rainbow-cliff.svg', 5.0, 1, 800, 600, 'image/svg+xml'),
('survey/redwood-forest.svg', 'redwood-forest.svg', 'https://cognitapi.s3.us-east-1.amazonaws.com/survey/redwood-forest.svg', 5.0, 1, 800, 600, 'image/svg+xml'),
('survey/river-canyon.svg', 'river-canyon.svg', 'https://cognitapi.s3.us-east-1.amazonaws.com/survey/river-canyon.svg', 5.0, 1, 800, 600, 'image/svg+xml'),
('survey/rolling-hills.svg', 'rolling-hills.svg', 'https://cognitapi.s3.us-east-1.amazonaws.com/survey/rolling-hills.svg', 5.0, 1, 800, 600, 'image/svg+xml'),
('survey/rose-castle.svg', 'rose-castle.svg', 'https://cognitapi.s3.us-east-1.amazonaws.com/survey/rose-castle.svg', 5.0, 1, 800, 600, 'image/svg+xml'),
('survey/saffron-market.svg', 'saffron-market.svg', 'https://cognitapi.s3.us-east-1.amazonaws.com/survey/saffron-market.svg', 5.0, 1, 800, 600, 'image/svg+xml'),
('survey/sample-normal.svg', 'sample-normal.svg', 'https://cognitapi.s3.us-east-1.amazonaws.com/survey/sample-normal.svg', 5.0, 1, 800, 600, 'image/svg+xml'),
('survey/sapphire-falls.svg', 'sapphire-falls.svg', 'https://cognitapi.s3.us-east-1.amazonaws.com/survey/sapphire-falls.svg', 5.0, 1, 800, 600, 'image/svg+xml'),
('survey/savanna-sunset.svg', 'savanna-sunset.svg', 'https://cognitapi.s3.us-east-1.amazonaws.com/survey/savanna-sunset.svg', 5.0, 1, 800, 600, 'image/svg+xml'),
('survey/sea-arch.svg', 'sea-arch.svg', 'https://cognitapi.s3.us-east-1.amazonaws.com/survey/sea-arch.svg', 5.0, 1, 800, 600, 'image/svg+xml'),
('survey/serene-pond.svg', 'serene-pond.svg', 'https://cognitapi.s3.us-east-1.amazonaws.com/survey/serene-pond.svg', 5.0, 1, 800, 600, 'image/svg+xml'),
('survey/silk-road.svg', 'silk-road.svg', 'https://cognitapi.s3.us-east-1.amazonaws.com/survey/silk-road.svg', 5.0, 1, 800, 600, 'image/svg+xml'),
('survey/silver-bridge.svg', 'silver-bridge.svg', 'https://cognitapi.s3.us-east-1.amazonaws.com/survey/silver-bridge.svg', 5.0, 1, 800, 600, 'image/svg+xml'),
('survey/starry-dunes.svg', 'starry-dunes.svg', 'https://cognitapi.s3.us-east-1.amazonaws.com/survey/starry-dunes.svg', 5.0, 1, 800, 600, 'image/svg+xml'),
('survey/sunlit-bay.svg', 'sunlit-bay.svg', 'https://cognitapi.s3.us-east-1.amazonaws.com/survey/sunlit-bay.svg', 5.0, 1, 800, 600, 'image/svg+xml'),
('survey/tropical-lagoon.svg', 'tropical-lagoon.svg', 'https://cognitapi.s3.us-east-1.amazonaws.com/survey/tropical-lagoon.svg', 5.0, 1, 800, 600, 'image/svg+xml'),
('survey/violet-harbor.svg', 'violet-harbor.svg', 'https://cognitapi.s3.us-east-1.amazonaws.com/survey/violet-harbor.svg', 5.0, 1, 800, 600, 'image/svg+xml'),
('survey/whispering-glade.svg', 'whispering-glade.svg', 'https://cognitapi.s3.us-east-1.amazonaws.com/survey/whispering-glade.svg', 5.0, 1, 800, 600, 'image/svg+xml')
ON CONFLICT (image_id) DO UPDATE SET
    s3_key = EXCLUDED.s3_key,
    s3_url = EXCLUDED.s3_url,
    difficulty_score = EXCLUDED.difficulty_score,
    object_count = EXCLUDED.object_count,
    width = EXCLUDED.width,
    height = EXCLUDED.height,
    content_type = EXCLUDED.content_type;