-- =====================================================================
-- C.O.G.N.I.T. Image Seed
-- Replaced with numbered SVG assets (1.svg ... 62.svg)
-- Safe to run multiple times (idempotent upserts)
-- =====================================================================

BEGIN;

INSERT INTO images (image_id, url, difficulty, object_count, width, height)
VALUES
    ('1.svg', 'https://cognitapi.s3.us-east-1.amazonaws.com/survey/1.svg', 5.0, 1, NULL, NULL),
    ('2.svg', 'https://cognitapi.s3.us-east-1.amazonaws.com/survey/2.svg', 4.0, 1, NULL, NULL),
    ('3.svg', 'https://cognitapi.s3.us-east-1.amazonaws.com/survey/3.svg', 5.0, 1, NULL, NULL),
    ('4.svg', 'https://cognitapi.s3.us-east-1.amazonaws.com/survey/4.svg', 5.0, 1, NULL, NULL),
    ('5.svg', 'https://cognitapi.s3.us-east-1.amazonaws.com/survey/5.svg', 5.0, 1, NULL, NULL),
    ('6.svg', 'https://cognitapi.s3.us-east-1.amazonaws.com/survey/6.svg', 5.0, 1, NULL, NULL),
    ('7.svg', 'https://cognitapi.s3.us-east-1.amazonaws.com/survey/7.svg', 4.0, 1, NULL, NULL),
    ('8.svg', 'https://cognitapi.s3.us-east-1.amazonaws.com/survey/8.svg', 5.0, 1, NULL, NULL),
    ('9.svg', 'https://cognitapi.s3.us-east-1.amazonaws.com/survey/9.svg', 4.0, 1, NULL, NULL),
    ('10.svg', 'https://cognitapi.s3.us-east-1.amazonaws.com/survey/10.svg', 5.0, 1, NULL, NULL),
    ('11.svg', 'https://cognitapi.s3.us-east-1.amazonaws.com/survey/11.svg', 5.0, 1, NULL, NULL),
    ('12.svg', 'https://cognitapi.s3.us-east-1.amazonaws.com/survey/12.svg', 5.0, 1, NULL, NULL),
    ('13.svg', 'https://cognitapi.s3.us-east-1.amazonaws.com/survey/13.svg', 5.0, 1, NULL, NULL),
    ('14.svg', 'https://cognitapi.s3.us-east-1.amazonaws.com/survey/14.svg', 5.0, 1, NULL, NULL),
    ('15.svg', 'https://cognitapi.s3.us-east-1.amazonaws.com/survey/15.svg', 5.0, 1, NULL, NULL),
    ('16.svg', 'https://cognitapi.s3.us-east-1.amazonaws.com/survey/16.svg', 5.0, 1, NULL, NULL),
    ('17.svg', 'https://cognitapi.s3.us-east-1.amazonaws.com/survey/17.svg', 5.0, 1, NULL, NULL),
    ('18.svg', 'https://cognitapi.s3.us-east-1.amazonaws.com/survey/18.svg', 5.0, 1, NULL, NULL),
    ('19.svg', 'https://cognitapi.s3.us-east-1.amazonaws.com/survey/19.svg', 5.0, 1, NULL, NULL),
    ('20.svg', 'https://cognitapi.s3.us-east-1.amazonaws.com/survey/20.svg', 4.0, 1, NULL, NULL),
    ('21.svg', 'https://cognitapi.s3.us-east-1.amazonaws.com/survey/21.svg', 5.0, 1, NULL, NULL),
    ('22.svg', 'https://cognitapi.s3.us-east-1.amazonaws.com/survey/22.svg', 5.0, 1, NULL, NULL),
    ('23.svg', 'https://cognitapi.s3.us-east-1.amazonaws.com/survey/23.svg', 5.0, 1, NULL, NULL),
    ('24.svg', 'https://cognitapi.s3.us-east-1.amazonaws.com/survey/24.svg', 5.0, 1, NULL, NULL),
    ('25.svg', 'https://cognitapi.s3.us-east-1.amazonaws.com/survey/25.svg', 5.0, 1, NULL, NULL),
    ('26.svg', 'https://cognitapi.s3.us-east-1.amazonaws.com/survey/26.svg', 5.0, 1, NULL, NULL),
    ('27.svg', 'https://cognitapi.s3.us-east-1.amazonaws.com/survey/27.svg', 5.0, 1, NULL, NULL),
    ('28.svg', 'https://cognitapi.s3.us-east-1.amazonaws.com/survey/28.svg', 5.0, 1, NULL, NULL),
    ('29.svg', 'https://cognitapi.s3.us-east-1.amazonaws.com/survey/29.svg', 5.0, 1, NULL, NULL),
    ('30.svg', 'https://cognitapi.s3.us-east-1.amazonaws.com/survey/30.svg', 5.0, 1, NULL, NULL),
    ('31.svg', 'https://cognitapi.s3.us-east-1.amazonaws.com/survey/31.svg', 5.0, 1, NULL, NULL),
    ('32.svg', 'https://cognitapi.s3.us-east-1.amazonaws.com/survey/32.svg', 5.0, 1, NULL, NULL),
    ('33.svg', 'https://cognitapi.s3.us-east-1.amazonaws.com/survey/33.svg', 5.0, 1, NULL, NULL),
    ('34.svg', 'https://cognitapi.s3.us-east-1.amazonaws.com/survey/34.svg', 5.0, 1, NULL, NULL),
    ('35.svg', 'https://cognitapi.s3.us-east-1.amazonaws.com/survey/35.svg', 5.0, 1, NULL, NULL),
    ('36.svg', 'https://cognitapi.s3.us-east-1.amazonaws.com/survey/36.svg', 5.0, 1, NULL, NULL),
    ('37.svg', 'https://cognitapi.s3.us-east-1.amazonaws.com/survey/37.svg', 5.0, 1, NULL, NULL),
    ('38.svg', 'https://cognitapi.s3.us-east-1.amazonaws.com/survey/38.svg', 5.0, 1, NULL, NULL),
    ('39.svg', 'https://cognitapi.s3.us-east-1.amazonaws.com/survey/39.svg', 5.0, 1, NULL, NULL),
    ('40.svg', 'https://cognitapi.s3.us-east-1.amazonaws.com/survey/40.svg', 5.0, 1, NULL, NULL),
    ('41.svg', 'https://cognitapi.s3.us-east-1.amazonaws.com/survey/41.svg', 5.0, 1, NULL, NULL),
    ('42.svg', 'https://cognitapi.s3.us-east-1.amazonaws.com/survey/42.svg', 5.0, 1, NULL, NULL),
    ('43.svg', 'https://cognitapi.s3.us-east-1.amazonaws.com/survey/43.svg', 5.0, 1, NULL, NULL),
    ('44.svg', 'https://cognitapi.s3.us-east-1.amazonaws.com/survey/44.svg', 5.0, 1, NULL, NULL),
    ('45.svg', 'https://cognitapi.s3.us-east-1.amazonaws.com/survey/45.svg', 5.0, 1, NULL, NULL),
    ('46.svg', 'https://cognitapi.s3.us-east-1.amazonaws.com/survey/46.svg', 5.0, 1, NULL, NULL),
    ('47.svg', 'https://cognitapi.s3.us-east-1.amazonaws.com/survey/47.svg', 4.0, 1, NULL, NULL),
    ('48.svg', 'https://cognitapi.s3.us-east-1.amazonaws.com/survey/48.svg', 5.0, 1, NULL, NULL),
    ('49.svg', 'https://cognitapi.s3.us-east-1.amazonaws.com/survey/49.svg', 5.0, 1, NULL, NULL),
    ('50.svg', 'https://cognitapi.s3.us-east-1.amazonaws.com/survey/50.svg', 5.0, 1, NULL, NULL),
    ('51.svg', 'https://cognitapi.s3.us-east-1.amazonaws.com/survey/51.svg', 4.0, 1, NULL, NULL),
    ('52.svg', 'https://cognitapi.s3.us-east-1.amazonaws.com/survey/52.svg', 5.0, 1, NULL, NULL),
    ('53.svg', 'https://cognitapi.s3.us-east-1.amazonaws.com/survey/53.svg', 5.0, 1, NULL, NULL),
    ('54.svg', 'https://cognitapi.s3.us-east-1.amazonaws.com/survey/54.svg', 4.0, 1, NULL, NULL),
    ('55.svg', 'https://cognitapi.s3.us-east-1.amazonaws.com/survey/55.svg', 5.0, 1, NULL, NULL),
    ('56.svg', 'https://cognitapi.s3.us-east-1.amazonaws.com/survey/56.svg', 5.0, 1, NULL, NULL),
    ('57.svg', 'https://cognitapi.s3.us-east-1.amazonaws.com/survey/57.svg', 5.0, 1, NULL, NULL),
    ('58.svg', 'https://cognitapi.s3.us-east-1.amazonaws.com/survey/58.svg', 5.0, 1, NULL, NULL),
    ('59.svg', 'https://cognitapi.s3.us-east-1.amazonaws.com/survey/59.svg', 5.0, 1, NULL, NULL),
    ('60.svg', 'https://cognitapi.s3.us-east-1.amazonaws.com/survey/60.svg', 5.0, 1, NULL, NULL),
    ('61.svg', 'https://cognitapi.s3.us-east-1.amazonaws.com/survey/61.svg', 5.0, 1, NULL, NULL),
    ('62.svg', 'https://cognitapi.s3.us-east-1.amazonaws.com/survey/62.svg', 5.0, 1, NULL, NULL)
ON CONFLICT (image_id) DO UPDATE SET
    url          = EXCLUDED.url,
    difficulty   = EXCLUDED.difficulty,
    object_count = EXCLUDED.object_count,
    width        = EXCLUDED.width,
    height       = EXCLUDED.height;

-- Difficulty overrides (source-of-truth mapping).
-- Keep the big INSERT simple; apply exact difficulty values here.
WITH desired_difficulty(image_id, difficulty) AS (
    VALUES
        ('1.svg', 5.0),
        ('2.svg', 4.0),
        ('3.svg', 5.0),
        ('4.svg', 5.0),
        ('5.svg', 4.0),
        ('6.svg', 5.0),
        ('7.svg', 4.0),
        ('8.svg', 5.0),
        ('9.svg', 5.0),
        ('10.svg', 4.0),
        ('11.svg', 5.0),
        ('12.svg', 3.0),
        ('13.svg', 5.0),
        ('14.svg', 2.0),
        ('15.svg', 3.0),
        ('16.svg', 4.0),
        ('17.svg', 3.0),
        ('18.svg', 5.0),
        ('19.svg', 4.0),
        ('20.svg', 4.0),
        ('21.svg', 5.0),
        ('22.svg', 2.0),
        ('23.svg', 2.0),
        ('24.svg', 3.0),
        ('25.svg', 2.0),
        ('26.svg', 1.0),
        ('27.svg', 1.0),
        ('28.svg', 1.0),
        ('29.svg', 1.0),
        ('30.svg', 1.0),
        ('31.svg', 1.0),
        ('32.svg', 2.0),
        ('33.svg', 3.0),
        ('34.svg', 3.0),
        ('35.svg', 3.0),
        ('36.svg', 5.0),
        ('37.svg', 5.0),
        ('38.svg', 5.0),
        ('39.svg', 5.0),
        ('40.svg', 5.0),
        ('41.svg', 4.0),
        ('42.svg', 5.0),
        ('43.svg', 5.0),
        ('44.svg', 5.0),
        ('45.svg', 5.0),
        ('46.svg', 4.0),
        ('47.svg', 4.0),
        ('48.svg', 4.0),
        ('49.svg', 5.0),
        ('50.svg', 5.0),
        ('51.svg', 4.0),
        ('52.svg', 4.0),
        ('53.svg', 5.0),
        ('54.svg', 4.0),
        ('55.svg', 2.0),
        ('56.svg', 2.0),
        ('57.svg', 3.0),
        ('58.svg', 4.0),
        ('59.svg', 3.0),
        ('60.svg', 5.0),
        ('61.svg', 5.0),
        ('62.svg', 5.0)
)
UPDATE images i
SET difficulty = d.difficulty
FROM desired_difficulty d
WHERE i.image_id = d.image_id;

WITH desired(image_key, expected_word, is_strict) AS (
    VALUES
        ('20.svg', 'cute, dog, animal, cartoon, illustration, stripes,,baby, eyes, soft, adorable, happy, nature, orange, playful, sweet,  calm, tiny, baby tiger, cute dog cartoon dog, dog cub, big eyes, orange stripes, nature theme, soft illustration, adorable animal, happy dog cute illustration, little dog , playful cub, gentle animal, tiny dog, lovely scene, peaceful nature', TRUE),
        ('11.svg', 'cute, deer , animal, cartoon, illustration, mane, jungle, wild, baby, eyes, soft, adorable, happy, nature, king, playful, sweet, forest, calm, tiny, baby lion, lion cub, cartoon lion, cute lion, big eyes, jungle animal, wild animal, fluffy mane, nature theme, soft illustration, adorable animal, happy lion, cute illustration, little lion, forest animal, playful cub, gentle animal, tiny lion, lovely scene, peaceful nature', TRUE),
        ('39.svg', 'cute, panda, animal, cartoon, illustration, trunk, ears, jungle, nature, baby, eyes, soft, adorable, happy, gray, playful, sweet, forest, calm, tiny, baby panda, cute elephant, cartoon elephant, big ears, long trunk, jungle animal, wild animal, gray animal, nature theme, soft illustration, adorable animal, happy elephant, cute illustration, little panda,, playful panda gentle animal, tiny panda lovely scene, peaceful nature', TRUE),
        ('18.svg', 'cute, bear, toy, cartoon, illustration, teddy, plush, soft, adorable, happy, baby, eyes, sweet, cozy, brown, fluffy, gift, love, calm, tiny, teddy bear, cute teddy, cartoon bear, plush toy, soft toy, baby toy, cute illustration, adorable toy, happy teddy, little bear, fluffy teddy, brown bear, cozy toy, love gift, honey jar, gentle toy, tiny teddy, lovely toy, soft plush, stuffed bear', TRUE),
        ('2.svg', 'cute, rabbit, animal, cartoon, illustration, bunny, ears, grass, nature, baby, eyes, soft, adorable, happy, white, fluffy, playful, sweet, garden, tiny, baby rabbit, cute rabbit, cartoon rabbit, big ears, fluffy bunny, garden animal, nature theme, soft illustration, adorable animal, happy bunny, cute illustration, little rabbit, grass field, playful bunny, gentle animal, tiny bunny, lovely scene, peaceful nature, white rabbit, bunny rabbit', TRUE),
        ('47.svg', 'cute, penguin, animal, cartoon, illustration, baby, eyes, soft, adorable, happy, black, white, playful, sweet, calm, fluffy, tiny, love, friendly, simple, baby panda, cute penguin , cartoon penguin, big eyes, fluffy penguin black white, cute illustration, adorable animal, happy penguin little panda, playful panda, gentle animal, tiny panda, lovely scene, soft colors, pastel style, simple design, friendly panda, cute style,coffee', TRUE),
        ('13.svg', 'cute, panda, animal, cartoon, illustration, pancake, blanket, baby, eyes, soft, adorable, happy, black, white, playful, sweet, calm, fluffy, tiny, cozy, baby panda, cute panda, cartoon panda, big eyes, fluffy panda, pancake food, pink blanket, cozy blanket, black white, cute illustration, adorable animal, happy panda, little panda, playful panda, gentle animal, tiny panda, lovely scene, soft colors, pastel style, cozy panda', TRUE),
        ('21.svg', 'dog, puppy, cute, cartoon, pet, animal, smile, happy, fluffy, scarf, flowers, garden, sun, nature, grass, soft, baby, playful, adorable, sweet, friendly, fur, ears, nose, eyes, tail, sitting, blossom, colorful, cheerful, little dog, cute puppy, happy pet, soft fur, cartoon dog, baby animal, flower garden, sunny day, smiling face, fluffy dog, playful puppy, adorable pet, sweet animal, friendly dog, colorful flowers, nature scene, sitting puppy, garden flowers, sunny background, cute animal', TRUE),
        ('37.svg', 'penguin, bird, animal, cute, cartoon, cold, snow, ice, winter, beak, flippers, black, white, small, baby, nature, antarctic, water, swim, chill, adorable, playful, happy, round, soft, tiny, walk, waddle, frozen, wildlife, cute penguin, baby penguin, cartoon penguin, fluffy bird, winter animal, cold habitat, icy land, snow background, playful penguin, adorable bird, small penguin, waddling penguin, antarctic animal, frozen scene, happy penguin, cute animal, soft body, tiny bird, wildlife scene', TRUE),
        ('38.svg', 'rabbit, rainbow, paint, brush, sky, stars, clouds, cute, colorful, night, white rabbit, rainbow painting, paint brush, starry sky, fluffy clouds, colorful arc, night scene, cute animal, artistic moment, dreamy background', TRUE),
        ('8.svg', 'deer, forest, grass, trees, nature, sky, sunlight, animal, calm, green, brown deer, forest scene, green grass, tall trees, natural habitat, peaceful nature, wild animal, outdoor scene, sunlight rays, serene environment ,cute ,pink flowers ,yellow flowers', TRUE),
        ('62.svg', 'mountain, house, snow, winter, sky, trees, cold, nature, calm, clouds, mountain house, snowy mountain, winter landscape, wooden house, alpine scene, peaceful place, snow covered, mountain view, cozy cabin, serene environment', TRUE),
        ('50.svg', 'dragon, fantasy, cute, glowing, magical, night, wings, crystals, flowers, stars, baby dragon, fantasy creature, glowing crystals, magical night, cute dragon, colorful flowers, sparkling stars, cartoon style, dreamy scene, mystical landscape', TRUE),
        ('51.svg', 'rabbit, bunny, cute, fluffy, ears, whiskers, nose, fur, small, soft, white rabbit, cute bunny, long ears, fluffy fur, small animal, soft texture, adorable pet, gentle creature, domestic rabbit, sweet face', TRUE),
        ('42.svg', 'rabbit, bunny, cute, fluffy, ears, whiskers, fur, nose, soft, small, cute bunny, baby rabbit, fluffy bunny, long ears, soft fur, small rabbit, white bunny, adorable rabbit, pet bunny, gentle rabbit', TRUE),
        ('6.svg', 'duck, duckling, bird, cute, yellow, beak, feathers, wings, small, soft, baby duck, cute duck, yellow duckling, small bird, soft feathers, tiny wings, adorable duck, water bird, fluffy duckling, gentle bird', TRUE),
        ('54.svg', 'deer, fawn, animal, wild, antlers, fur, legs, forest, eyes, graceful, baby deer, young fawn, wild animal, brown fur, forest animal, gentle deer, small fawn, elegant animal, woodland creature, cute deer', TRUE),
        ('36.svg', 'abstract, blue, gradient, shape, pattern, texture, design, object, tree, sun, sky, smooth, curve, wave, flow, soft, dark, light, simple, clean, color, shadow, layer, modern, blue object, abstract object, green tree, bright sun, blue sky, smooth curve, soft gradient, simple design, clean pattern, light texture, dark shade, color blend, layered shape, modern style', TRUE),
        ('4.svg', 'fox, cute fox, cartoon fox, animal, character, eyes, big eyes, glossy eyes, cheeks, blush cheeks, scarf, winter, orange fox, small fox, soft fur, fluffy tail, sitting fox, adorable fox, winter scarf, cute animal', TRUE),
        ('53.svg', 'cat, cute cat, cartoon cat, small cat, pet cat, fluffy, soft fur, round face, small ears, whiskers, paws, adorable, animal, character, big eyes, dark blue eyes, shiny eyes, pink nose, flower, pink flower, cute animal, sitting cat, smiling cat, baby cat, chubby cat, sweet expression ,cup', TRUE),
        ('44.svg', 'fox, red fox, cute fox, cartoon fox, woodland fox, forest predator, wild fox, animal, orange fur, fluffy tail, pointy ears, big eyes, shiny eyes, small nose, sitting fox, adorable fox, baby fox, autumn, fall season, orange leaves, forest scene, nature, enjoy nature, mushroom, woodland animal', TRUE),
        ('1.svg', 'cat, cute, pastel, soft, floral, kawaii, kitten, bow, pink, cream, petals, nature, adorable, cartoon, sweet, calm, aesthetic, baby, gentle, animal, cute cat, pastel colors, soft tones, floral design, kawaii style, baby kitten, pink bow, cream fur, flower garden, cartoon cat, adorable kitten, gentle vibe, sweet aesthetic, nature theme, soft petals, cute animal, calm mood, floral background', TRUE),
        ('49.svg', 'panda, picnic, cupcake, butterflies, flowers, meadow, sunny, illustration, cartoon, blanket, giant panda, picnic blanket, red butterfly, sweet cupcake, spring meadow, blue sky, picnic basket, wild flowers, cute animal, outdoor scene', TRUE),
        ('45.svg', 'koala, moon, stars, clouds, night, fluffy, whimsical, dreamy, illustration, nocturnal, crescent moon, night sky, golden stars, cute koala, tree branch, digital art, blue clouds, starry night, sleepy animal', TRUE),
        ('60.svg', 'bunny, astronaut, space, galaxy, planets, stars, helmet, cute, illustration, cartoon, space bunny, rabbit astronaut, blue spacesuit, glass helmet, distant planets, shining stars, purple background, digital art, whimsical character, outer space', TRUE),
        ('43.svg', 'dragon, fantasy, moon, night, wings, fire, magic, crystals, creature, stars, fantasy dragon, night sky, glowing crystals, magical creature, flying dragon, dragon wings, moon light, fantasy art, fire dragon, crystal cave', TRUE),
        ('3.svg', 'panda, cupcake, garden, cartoon, cute, animal, flowers, tree, butterflies, picnic, cute panda, cartoon panda, eating cupcake, garden scene, baby panda, sweet dessert, flower garden, outdoor picnic, cute animal, pastel colors', TRUE),
        ('61.svg', 'dragon, crystals, flowers, mountains, rock, wings, stars, clouds, teal, whimsical, baby dragon, pink flowers, crystal shards, mountain peaks, digital illustration, fantasy creature, mythical beast, blue dragon, starry sky, cute character', TRUE),
        ('9.svg', 'penguin, winter, scarf, snow, cartoon, cute, animal, cold, baby, pastel, cute penguin, baby penguin, winter scarf, snowy background, cartoon animal, cold weather, kawaii style, winter animal, cute cartoon, snow scene', TRUE),
        ('7.svg', 'elephant, balloons, cartoon, cute, animal, baby, pink, toy, smile, pastel, cute elephant, baby elephant, pink balloons, cartoon animal, cute cartoon, pastel colors, holding balloons, kawaii style, happy animal, nursery art', TRUE)
),
mapped AS (
    SELECT i.id AS image_db_id, d.expected_word, d.is_strict
    FROM desired d
    JOIN images i ON i.image_id = d.image_key
),
updated AS (
    UPDATE attention_checks ac
    SET expected_word = m.expected_word,
        is_strict     = m.is_strict,
        is_active     = TRUE
    FROM mapped m
    WHERE ac.image_id = m.image_db_id
    RETURNING 1
),
inserted AS (
    INSERT INTO attention_checks (image_id, expected_word, is_strict, is_active)
    SELECT m.image_db_id, m.expected_word, m.is_strict, TRUE
    FROM mapped m
    LEFT JOIN attention_checks ac ON ac.image_id = m.image_db_id
    WHERE ac.image_id IS NULL
    RETURNING 1
)
SELECT
    (SELECT COUNT(*) FROM updated)  AS updated_rows,
    (SELECT COUNT(*) FROM inserted) AS inserted_rows;

WITH ground_truth(image_key, object_name, is_present) AS (
    VALUES
        ('1.svg', 'Cat', TRUE),
        ('1.svg', 'Flower', TRUE),
        ('2.svg', 'Rabbit', TRUE),
        ('2.svg', 'Carrot', TRUE),
        ('2.svg', 'Grass', TRUE),
        ('3.svg', 'Panda', TRUE),
        ('3.svg', 'Grass', TRUE),
        ('4.svg', 'Fox', TRUE),
        ('4.svg', 'Mushroom', TRUE),
        ('4.svg', 'Tree', TRUE),
        ('5.svg', 'Kawaii', TRUE),
        ('5.svg', 'Tree', TRUE),
        ('6.svg', 'Duck', TRUE),
        ('6.svg', 'Water', TRUE),
        ('6.svg', 'Flower', TRUE),
        ('7.svg', 'Elephant', TRUE),
        ('7.svg', 'Balloon', TRUE),
        ('8.svg', 'Deer', TRUE),
        ('8.svg', 'Flower', TRUE),
        ('8.svg', 'Butterfly', TRUE),
        ('9.svg', 'Penguin', TRUE),
        ('9.svg', 'Winter', TRUE),
        ('9.svg', 'Snow', TRUE),
        ('10.svg', 'Rabbit', TRUE),
        ('10.svg', 'Sun', TRUE),
        ('10.svg', 'Grass', TRUE),
        ('11.svg', 'Deer', TRUE),
        ('11.svg', 'Flower', TRUE),
        ('11.svg', 'Butterfly', TRUE),
        ('12.svg', 'Wheel', TRUE),
        ('13.svg', 'Panda', TRUE),
        ('13.svg', 'Grass', TRUE),
        ('13.svg', 'Mountain', TRUE),
        ('14.svg', 'River', TRUE),
        ('14.svg', 'Mountain', TRUE),
        ('14.svg', 'Sun', TRUE),
        ('15.svg', 'Bunny', TRUE),
        ('15.svg', 'Rabbit', TRUE),
        ('15.svg', 'Carrot', TRUE),
        ('15.svg', 'Rainbow', TRUE),
        ('16.svg', 'Lion', TRUE),
        ('16.svg', 'Grass', TRUE),
        ('17.svg', 'Cat', TRUE),
        ('17.svg', 'Butterfly', TRUE),
        ('18.svg', 'Panda', TRUE),
        ('18.svg', 'Honeybee', TRUE),
        ('18.svg', 'Honey', TRUE),
        ('18.svg', 'Flower', TRUE),
        ('19.svg', 'Owl', TRUE),
        ('19.svg', 'Sun', TRUE),
        ('19.svg', 'Tree', TRUE),
        ('20.svg', 'Puppy', TRUE),
        ('20.svg', 'Dog', TRUE),
        ('20.svg', 'Basket', TRUE),
        ('20.svg', 'Flower', TRUE),
        ('21.svg', 'Puppy', TRUE),
        ('21.svg', 'Dog', TRUE),
        ('21.svg', 'Sun', TRUE),
        ('21.svg', 'Mountain', TRUE),
        ('21.svg', 'Flower', TRUE),
        ('22.svg', 'Round', TRUE),
        ('23.svg', 'River', TRUE),
        ('23.svg', 'Mountain', TRUE),
        ('23.svg', 'Sun', TRUE),
        ('24.svg', 'Rabbit', TRUE),
        ('24.svg', 'Sun', TRUE),
        ('24.svg', 'Grass', TRUE),
        ('24.svg', 'Butterfly', TRUE),
        ('25.svg', 'Cat', TRUE),
        ('25.svg', 'Sun', TRUE),
        ('26.svg', 'Bear', TRUE),
        ('27.svg', 'Bunny', TRUE),
        ('28.svg', 'Bear', TRUE),
        ('29.svg', 'Cat', TRUE),
        ('30.svg', 'Bear', TRUE),
        ('31.svg', 'Panda', TRUE),
        ('32.svg', 'Teddy', TRUE),
        ('33.svg', 'Puppy', TRUE),
        ('33.svg', 'Dog', TRUE),
        ('33.svg', 'Sun', TRUE),
        ('34.svg', 'Cat', TRUE),
        ('35.svg', 'Dog', TRUE),
        ('36.svg', 'Tree', TRUE),
        ('36.svg', 'Sun', TRUE),
        ('36.svg', 'Mountain', TRUE),
        ('37.svg', 'Penguin', TRUE),
        ('37.svg', 'Winter', TRUE),
        ('37.svg', 'Snow', TRUE),
        ('37.svg', 'Tree', TRUE),
        ('38.svg', 'Rabbit', TRUE),
        ('38.svg', 'Rainbow', TRUE),
        ('38.svg', 'Cloud', TRUE),
        ('38.svg', 'Star', TRUE),
        ('39.svg', 'Panda', TRUE),
        ('39.svg', 'Cake', TRUE),
        ('39.svg', 'Grass', TRUE),
        ('39.svg', 'Flower', TRUE),
        ('39.svg', 'Tree', TRUE),
        ('40.svg', 'Cat', TRUE),
        ('40.svg', 'Grass', TRUE),
        ('40.svg', 'Flower', TRUE),
        ('40.svg', 'Butterfly', TRUE),
        ('41.svg', 'Elephant', TRUE),
        ('41.svg', 'Balloon', TRUE),
        ('41.svg', 'Sky', TRUE),
        ('41.svg', 'Grass', TRUE),
        ('41.svg', 'Flower', TRUE),
        ('42.svg', 'Rabbit', TRUE),
        ('42.svg', 'Space', TRUE),
        ('42.svg', 'Star', TRUE),
        ('42.svg', 'Planet', TRUE),
        ('42.svg', 'Cloud', TRUE),
        ('43.svg', 'Dragon', TRUE),
        ('43.svg', 'Star', TRUE),
        ('43.svg', 'Moon', TRUE),
        ('44.svg', 'Fox', TRUE),
        ('44.svg', 'Grass', TRUE),
        ('44.svg', 'Tree', TRUE),
        ('44.svg', 'Mushroom', TRUE),
        ('44.svg', 'Flower', TRUE),
        ('45.svg', 'Koala', TRUE),
        ('45.svg', 'Star', TRUE),
        ('45.svg', 'Moon', TRUE),
        ('45.svg', 'Cloud', TRUE),
        ('46.svg', 'Koala', TRUE),
        ('46.svg', 'Sun', TRUE),
        ('46.svg', 'Tree', TRUE),
        ('46.svg', 'Cloud', TRUE),
        ('47.svg', 'Penguin', TRUE),
        ('47.svg', 'Tea', TRUE),
        ('47.svg', 'Cup', TRUE),
        ('47.svg', 'Coffee', TRUE),
        ('48.svg', 'Rabbit', TRUE),
        ('48.svg', 'Space', TRUE),
        ('48.svg', 'Star', TRUE),
        ('48.svg', 'Planet', TRUE),
        ('49.svg', 'Panda', TRUE),
        ('49.svg', 'Sky', TRUE),
        ('49.svg', 'Grass', TRUE),
        ('49.svg', 'Flower', TRUE),
        ('49.svg', 'Cake', TRUE),
        ('49.svg', 'Butterfly', TRUE),
        ('49.svg', 'Cloud', TRUE),
        ('50.svg', 'Dragon', TRUE),
        ('50.svg', 'Star', TRUE),
        ('50.svg', 'Flower', TRUE),
        ('51.svg', 'Rabbit', TRUE),
        ('51.svg', 'Sky', TRUE),
        ('51.svg', 'Cloud', TRUE),
        ('51.svg', 'Rainbow', TRUE),
        ('52.svg', 'Elephant', TRUE),
        ('53.svg', 'Cat', TRUE),
        ('53.svg', 'Flower', TRUE),
        ('54.svg', 'Fox', TRUE),
        ('54.svg', 'Mountain', TRUE),
        ('54.svg', 'Tree', TRUE),
        ('54.svg', 'Sky', TRUE),
        ('55.svg', 'Kawaii', TRUE),
        ('55.svg', 'Sky', TRUE),
        ('55.svg', 'Cloud', TRUE),
        ('56.svg', 'Turtle', TRUE),
        ('56.svg', 'Water', TRUE),
        ('56.svg', 'River', TRUE),
        ('57.svg', 'Bunny', TRUE),
        ('57.svg', 'Rabbit', TRUE),
        ('57.svg', 'Carrot', TRUE),
        ('57.svg', 'Star', TRUE),
        ('58.svg', 'Fox', TRUE),
        ('58.svg', 'Tree', TRUE),
        ('59.svg', 'Cat', TRUE),
        ('60.svg', 'Bunny', TRUE),
        ('60.svg', 'Rabbit', TRUE),
        ('60.svg', 'Star', TRUE),
        ('60.svg', 'Planet', TRUE),
        ('61.svg', 'Dragon', TRUE),
        ('61.svg', 'Flower', TRUE),
        ('61.svg', 'Sky', TRUE),
        ('61.svg', 'Cloud', TRUE),
        ('62.svg', 'Mountain', TRUE),
        ('62.svg', 'Home', TRUE),
        ('62.svg', 'Tree', TRUE),
        ('62.svg', 'Cloud', TRUE),
        ('62.svg', 'Sky', TRUE)
),
ground_mapped AS (
    SELECT i.id AS image_db_id, g.object_name, g.is_present
    FROM ground_truth g
    JOIN images i ON i.image_id = g.image_key
),
ground_updated AS (
    UPDATE ground_truth_labels gt
    SET is_present = gm.is_present
    FROM ground_mapped gm
    WHERE gt.image_id = gm.image_db_id
      AND gt.object = gm.object_name
    RETURNING 1
),
ground_inserted AS (
    INSERT INTO ground_truth_labels (image_id, object, is_present)
    SELECT gm.image_db_id, gm.object_name, gm.is_present
    FROM ground_mapped gm
    LEFT JOIN ground_truth_labels gt
        ON gt.image_id = gm.image_db_id AND gt.object = gm.object_name
    WHERE gt.image_id IS NULL
    RETURNING 1
)
SELECT
    (SELECT COUNT(*) FROM ground_updated)  AS ground_updated_rows,
    (SELECT COUNT(*) FROM ground_inserted) AS ground_inserted_rows;

COMMIT;
