from typing import Dict, Set

from app.constants.participant_constants import (
    PARTICIPANT_PAYMENT_STATUS_FAILED,
    PARTICIPANT_PAYMENT_STATUS_PENDING,
    PARTICIPANT_PAYMENT_STATUS_PAID,
    PARTICIPANT_PAYMENT_STATUS_REFUNDED,
    PARTICIPANT_STAGE_PAYMENT,
    PARTICIPANT_STAGE_FINISHED,
    PARTICIPANT_STAGE_SURVEY,
)
from app.constants.payment_constants import (
    PAYMENT_STATUS_EXPIRED,
    PAYMENT_STATUS_FAILED,
    PAYMENT_STATUS_PENDING,
    PAYMENT_STATUS_PROCESSING,
    PAYMENT_STATUS_REFUNDED,
    PAYMENT_STATUS_REJECTED_FRAUD,
    PAYMENT_STATUS_SUCCESS,
)

PAYMENT_STATUS_TRANSITIONS: Dict[str, Set[str]] = {
    PAYMENT_STATUS_PENDING: {PAYMENT_STATUS_PROCESSING, PAYMENT_STATUS_EXPIRED, PAYMENT_STATUS_FAILED, PAYMENT_STATUS_REJECTED_FRAUD},
    PAYMENT_STATUS_PROCESSING: {PAYMENT_STATUS_SUCCESS, PAYMENT_STATUS_REJECTED_FRAUD, PAYMENT_STATUS_FAILED},
    PAYMENT_STATUS_SUCCESS: set(),
    PAYMENT_STATUS_REJECTED_FRAUD: set(),
    PAYMENT_STATUS_EXPIRED: set(),
    PAYMENT_STATUS_FAILED: set(),
    PAYMENT_STATUS_REFUNDED: set(),
}

SUBMISSION_WORKFLOW_ALLOWED_STAGES_BY_PAYMENT: Dict[str, Set[str]] = {
    PARTICIPANT_PAYMENT_STATUS_PAID: {PARTICIPANT_STAGE_SURVEY, PARTICIPANT_STAGE_FINISHED},
}


def participant_state_for_payment_status(status: str) -> tuple[str, str]:
    normalized = (status or "").strip().lower()
    if normalized == PAYMENT_STATUS_SUCCESS:
        return PARTICIPANT_PAYMENT_STATUS_PAID, PARTICIPANT_STAGE_SURVEY
    if normalized in {PAYMENT_STATUS_FAILED, PAYMENT_STATUS_EXPIRED, PAYMENT_STATUS_REJECTED_FRAUD}:
        return PARTICIPANT_PAYMENT_STATUS_FAILED, PARTICIPANT_STAGE_PAYMENT
    if normalized == PAYMENT_STATUS_REFUNDED:
        return PARTICIPANT_PAYMENT_STATUS_REFUNDED, PARTICIPANT_STAGE_PAYMENT
    return PARTICIPANT_PAYMENT_STATUS_PENDING, PARTICIPANT_STAGE_PAYMENT
