"""Cache and short-lived data config section."""

APP_CACHE_URL = ""
APP_CACHE_TTL_SECONDS = 60
PARTICIPANT_OPTIONS_CACHE_TTL_SECONDS = 3600
IMAGE_POOL_CACHE_TTL_SECONDS = 60
IMAGE_RESERVATION_TTL_SECONDS = 900
IMAGE_RESERVATION_CLEANUP_EXPIRES_AT_DEFAULT = 0.0
