"""Observability, logging, async worker and queue config section."""

from __future__ import annotations

from .env import bool_env, int_env, str_env, truthy_env


LOG_LEVEL = "INFO"
LOGGING_AUTO_CONFIG = True
SUPPRESS_ACCESS_LOGS = bool_env("SUPPRESS_ACCESS_LOGS", True)
RUNNING_ON_VERCEL = truthy_env("VERCEL")
APP_PROCESS_ROLE = str_env("APP_PROCESS_ROLE", "web" if RUNNING_ON_VERCEL else "all", choices={"web", "worker", "all"})

API_LATENCY_SLO_MS = 1200

ENABLE_DEVICE_FINGERPRINTING = bool_env("ENABLE_DEVICE_FINGERPRINTING", True)
ENABLE_AUDIT_LOGGING = bool_env("ENABLE_AUDIT_LOGGING", True)
ENABLE_ERROR_LOGGING = bool_env("ENABLE_ERROR_LOGGING", True)
ENABLE_REQUEST_DB_OBSERVABILITY = bool_env("ENABLE_REQUEST_DB_OBSERVABILITY", not RUNNING_ON_VERCEL)
DEVICE_FINGERPRINT_SALTS = str_env("DEVICE_FINGERPRINT_SALTS", "cognit_fingerprint_salt_2024")

ENABLE_DURABLE_EVENT_QUEUE = bool_env("ENABLE_DURABLE_EVENT_QUEUE", True)
START_DURABLE_EVENT_WORKER = ENABLE_DURABLE_EVENT_QUEUE and APP_PROCESS_ROLE in {"worker", "all"}
DURABLE_EVENT_QUEUE_POLL_MS = 750
DURABLE_EVENT_QUEUE_MAX_ATTEMPTS = 8
DURABLE_EVENT_QUEUE_BASE_BACKOFF_MS = 1000
DURABLE_EVENT_QUEUE_MAX_BACKOFF_MS = 60000
DURABLE_EVENT_QUEUE_MIN_BACKOFF_MS = 100
DURABLE_EVENT_QUEUE_IDLE_SLEEP_MS = 100
DURABLE_EVENT_QUEUE_BUSY_SLEEP_MS = 10

ASYNC_EXECUTOR_WORKERS_EMAIL_OTP = 4
ASYNC_EXECUTOR_WORKERS_SUBMISSION_POST_COMMIT = 4
ASYNC_EXECUTOR_WORKERS_OBSERVABILITY = 2

EMAIL_OTP_ASYNC_MAX_ATTEMPTS = 3
EMAIL_OTP_ASYNC_BASE_BACKOFF_MS = 500
EMAIL_OTP_ASYNC_MAX_BACKOFF_MS = 10000
SUBMISSION_POST_COMMIT_ASYNC_MAX_ATTEMPTS = 3
SUBMISSION_POST_COMMIT_ASYNC_BASE_BACKOFF_MS = 250
SUBMISSION_POST_COMMIT_ASYNC_MAX_BACKOFF_MS = 60000
OBS_ASYNC_MAX_ATTEMPTS = 2
OBS_ASYNC_BASE_BACKOFF_MS = 100

PORT = int_env("PORT", 5000, min_value=1, max_value=65535)
FLASK_DEBUG = bool_env("FLASK_DEBUG", True)

ROOT_RATE_LIMIT = "60 per minute"
DOCS_RATE_LIMIT = "30 per minute"
HEALTH_RATE_LIMIT = "20 per minute"
PARTICIPANT_CREATE_RATE_LIMIT = "80 per minute"
PARTICIPANT_CHECK_RATE_LIMIT = "60 per minute"
PARTICIPANT_SESSION_RATE_LIMIT = "60 per minute"
IMAGES_RANDOM_RATE_LIMIT = "240 per minute"
CONSENT_RATE_LIMIT = "80 per minute"
SUBMIT_RATE_LIMIT = "120 per minute"
EMAIL_OTP_REQUEST_RATE_LIMIT = "40 per hour"
EMAIL_OTP_VERIFY_RATE_LIMIT = "40 per minute"
