const toInt = (value, fallback) => {
  const num = Number.parseInt(String(value ?? ""), 10);
  return Number.isFinite(num) ? num : fallback;
};

const toBool = (value, fallback = false) => {
  if (value === undefined || value === null || value === "") return fallback;
  return String(value).toLowerCase() === "true";
};

const toList = (value, fallback = []) => {
  if (value === undefined || value === null) return fallback;
  const raw = String(value).trim();
  if (!raw) return fallback;
  const parts = raw.split(/[|,]/g).map((p) => p.trim()).filter(Boolean);
  return parts.length ? parts : fallback;
};

export const runtimeConfig = {
  msPerSecond: 1000,
  countdownTickMs: 1000,
  dataCollectionEndsAtIso: String(import.meta.env.VITE_DATA_COLLECTION_ENDS_AT || "2026-04-09T00:00:00+05:30").trim(),
  uiStateSchemaVersion: 1,
  uiStateTtlMs: 3600000,
  // Auto-clean all stored state after 60 minutes.
  piiStateTtlMs: 3600000,
  activeTabLockSchemaVersion: 1,
  activeTabHeartbeatMs: 4000,
  activeTabStaleMs: 15000,
  toastDedupeWindowMs: 2000,
  toastAutoDismissMs: 4000,
  toastMaxStack: 4,
  toastReplaceWindowMs: 1500,
  toastPriority: {
    error: 3,
    warning: 2,
    success: 1,
    info: 0,
  },
  confettiDurationMs: 1200,
  serviceRetrySeconds: 8,
  serviceRetryMaxAttempts: 4,
  serviceReplacementMaxAttempts: 2,
  clientErrorMaxQueue: 20,
  clientErrorMaxFieldLength: 600,
  clientErrorMaxSendAttempts: 5,
  clientErrorMaxBackoffMs: 30000,
  clientErrorBlockCooldownMs: 900000,
  turnstileEnabled: toBool(import.meta.env.VITE_TURNSTILE_ENABLED, false),
  turnstileSiteKey: String(import.meta.env.VITE_TURNSTILE_SITE_KEY || "").trim(),
  turnstileClientTimeoutMs: 9000,
  turnstileClientMaxAttempts: 3,
  turnstilePrefetchTtlMs: 45000,
  emailOtpLength: 6,
  emailOtpExpirySeconds: 300,
  emailOtpResendCooldownSeconds: 30,
  otpStatus: {
    idle: "idle",
    sending: "sending",
    sent: "sent",
    sendFailed: "send_failed",
    verifying: "verifying",
    verifyFailed: "verify_failed",
    verified: "verified",
  },
  emailPlaceholderRotateMs: toInt(import.meta.env.VITE_EMAIL_PLACEHOLDER_ROTATE_MS, 1800),
  focusAdvanceDelayMs: 0,
  allowedEmailDomains: toList(import.meta.env.VITE_ALLOWED_EMAIL_DOMAINS, []),
  storageKeys: {
    activeTabLock: "cognit_active_tab_lock_v1",
    darkMode: "darkMode",
    stage: "stage",
    consentGiven: "consentGiven",
    userDetailsSubmitted: "userDetailsSubmitted",
    emailVerified: "emailVerified",
    demographics: "demographics",
    survey: "survey",
    surveyLoadState: "surveyLoadState",
    surveyCompleted: "surveyCompleted",
    surveyFeedbackReady: "surveyFeedbackReady",
    lastSubmissionSucceeded: "lastSubmissionSucceeded",
    shownImages: "shownImages",
    sessionId: "sessionId",
    publicId: "publicId",
    preAuthId: "preAuthId",
    consentDraft: "consent_checked_draft",
    consentPending: "consent_pending_submit_v1",
    userDetailsPending: "user_details_pending_submit_v1",
    emailOtpState: "email_otp_state_v1",
    participantOptions: "participant_options_v1",
    autoLocationPrompt: "location_auto_prompt_v1",
    autoLocationSuccess: "location_auto_success_v1",
    desktopLocationSession: "desktop_location_session_v1",
    reverseGeocodeState: "reverse_geocode_state_v1",
    surveyDraftPrefix: "survey_draft",
    surveyDraftActivePrefix: "survey_draft_active",
    surveyPendingSubmit: "survey_pending_submit_v1",
    surveyFeedPendingContinue: "survey_feed_pending_continue_v1",
    surveyFeedPendingFinish: "survey_feed_pending_finish_v1",
    telemetry: "client_telemetry_v1",
    clientErrorQueue: "client_error_queue_v1",
    telemetryBlocked: "client_telemetry_blocked_v1",
    clearOnClose: "clear_on_close_v1",
    sessionAlive: "session_alive_v1",
    preAuthMigrationLock: "preauth_migration_lock_v1",
    preAuthMigrationDonePrefix: "preauth_migration_done_v1",
  },
  preAuthMigrationLockTtlMs: 10000,
  preAuthMigrationDoneTtlMs: 86400000,
  surveyDraftSchemaVersion: 1,
  consentDraftSchemaVersion: 1,
  consentDraftTtlMs: 3600000,
  disableCopyPaste: toBool(import.meta.env.VITE_DISABLE_COPY_PASTE, true),
  minWords: toInt(import.meta.env.VITE_MIN_WORDS, 60),
  minDescriptionLength: toInt(import.meta.env.VITE_MIN_DESCRIPTION_LENGTH, 60),
  maxDescriptionLength: toInt(import.meta.env.VITE_MAX_DESCRIPTION_LENGTH, 10000),
  minFeedbackLength: toInt(import.meta.env.VITE_MIN_FEEDBACK_LENGTH, 5),
  maxFeedbackLength: toInt(import.meta.env.VITE_MAX_FEEDBACK_LENGTH, 2000),
  minRating: toInt(import.meta.env.VITE_MIN_RATING, 1),
  maxRating: toInt(import.meta.env.VITE_MAX_RATING, 5),
  requiredSurveySubmissions: 2,
  surveyUiTotalSteps: 2,
  submitUnlockDelayMs: 900,
  submitUnlockInvalidDelayMs: 500,
  submitUnlockCompleteDelayMs: 1000,
  accountFlaggedRedirectDelayMs: 4000,
  surveyTimerTickMs: 1000,
  sessionValidationCooldownMs: 10000,
  sessionValidationBootGraceMs: 3000,
  healthCheckTimeoutMs: 10000,
  healthCheckIntervalMs: 30000,
  networkProbeTimeoutMs: 4000,
  networkProbeIntervalMs: 10000,
  networkProbeFailThreshold: 2,
  geolocationTimeoutMs: 10000,
  geolocationMaxAgeMs: 300000,
  reverseGeocodeUrl: "https://nominatim.openstreetmap.org/reverse",
  reverseGeocodeTtlMs: 300000,
  availabilityDebounceMs: 500,
  usernameMinLength: toInt(import.meta.env.VITE_USERNAME_MIN_LENGTH, 2),
  ageMin: toInt(import.meta.env.VITE_AGE_MIN, 13),
  ageMax: toInt(import.meta.env.VITE_AGE_MAX, 100),
  locationMinLength: toInt(import.meta.env.VITE_LOCATION_MIN_LENGTH, 2),
};
