export const ACTIVE_TAB_LOCK_FIELDS = {
  tabId: "tab_id",
  updatedAt: "updated_at",
};

export const SURVEY_API_FIELDS = {
  imageId: "image_id",
  imageUrl: "image_url",
  url: "url",
  isSurvey: "is_survey",
  isAttentionCheck: "is_attention_check",
  attentionStatus: "attention_status",
  attentionPassed: "attention_passed",
  hardFlagTriggered: "hard_flag_triggered",
  surveyIndex: "survey_index",
  publicId: "public_id",
  timeSpentSeconds: "time_spent_seconds",
  tabSwitchCount: "tab_switch_count",
  pageCloseAttempts: "page_close_attempts",
  networkDisconnects: "network_disconnects",
  surveyTimeSpentMs: "survey_time_spent_ms",
  surveyPageViews: "survey_page_views",
  surveyTabSwitches: "survey_tab_switches",
  surveyPageCloseAttempts: "survey_page_close_attempts",
  surveyNetworkDisconnects: "survey_network_disconnects",
  surveyMaxScrollDepthPct: "survey_max_scroll_depth_pct",
  surveyClicks: "survey_clicks",
  surveyKeypresses: "survey_keypresses",
  failureReasons: "failure_reasons",
};
