export const ACTIVE_TAB_LOCK_FIELDS = {
  tabId: "tab_id",
  updatedAt: "updated_at",
};

export const SURVEY_API_FIELDS = {
  imageId: "image_id",
  imageUrl: "image_url",
  url: "url",
  isSurvey: "is_survey",
  isAttentionCheck: "is_attention_check",
  attentionStatus: "attention_status",
  attentionPassed: "attention_passed",
  hardFlagTriggered: "hard_flag_triggered",
  surveyIndex: "survey_index",
  publicId: "public_id",
  sessionId: "session_id",
  timeSpentSeconds: "time_spent_seconds",
  tabSwitchCount: "tab_switch_count",
  pageCloseAttempts: "page_close_attempts",
  networkDisconnects: "network_disconnects",
  surveyTimeSpentSeconds: "survey_time_spent_seconds",
  surveyPageViews: "survey_page_views",
  surveyTabSwitches: "survey_tab_switches",
  surveyPageCloseAttempts: "survey_page_close_attempts",
  surveyNetworkDisconnects: "survey_network_disconnects",
  surveyMaxScrollDepthPct: "survey_max_scroll_depth_pct",
  surveyClicks: "survey_clicks",
  surveyKeypresses: "survey_keypresses",
  confidenceScore: "confidence_score",
  difficultySelfReport: "difficulty_self_report",
  timeBeforeTypingSeconds: "time_before_typing_seconds",
  editCount: "edit_count",
  backspaceCount: "backspace_count",
  firstViewDurationSeconds: "first_view_duration_seconds",
  writingDurationSeconds: "writing_duration_seconds",
  avgKeystrokeIntervalSeconds: "avg_keystroke_interval_seconds",
  keystrokeVariance: "keystroke_variance",
  pauseCount: "pause_count",
  avgPauseDurationSeconds: "avg_pause_duration_seconds",
  failureReasons: "failure_reasons",
};
