"""
Configuration module for C.O.G.N.I.T. backend.
Central export layer composed from logical config sections.
"""

from __future__ import annotations

from typing import Any, Dict

from app.constants.error_codes import build_error_codes
from app.config_sections import cache as cache_cfg
from app.config_sections import db as db_cfg
from app.config_sections import env as env_cfg
from app.config_sections import observability as obs_cfg
from app.config_sections import security as sec_cfg
from app.config_sections import survey as survey_cfg

# Cache section
APP_CACHE_TTL_SECONDS = cache_cfg.APP_CACHE_TTL_SECONDS
APP_CACHE_URL = cache_cfg.APP_CACHE_URL
IMAGE_POOL_CACHE_TTL_SECONDS = cache_cfg.IMAGE_POOL_CACHE_TTL_SECONDS
IMAGE_RESERVATION_TTL_SECONDS = cache_cfg.IMAGE_RESERVATION_TTL_SECONDS
IMAGE_RESERVATION_CLEANUP_EXPIRES_AT_DEFAULT = cache_cfg.IMAGE_RESERVATION_CLEANUP_EXPIRES_AT_DEFAULT
PARTICIPANT_OPTIONS_CACHE_TTL_SECONDS = cache_cfg.PARTICIPANT_OPTIONS_CACHE_TTL_SECONDS

# DB section
DATABASE_SSLMODE = db_cfg.DATABASE_SSLMODE
DATABASE_URL = db_cfg.DATABASE_URL
DB_MAX_OVERFLOW = db_cfg.DB_MAX_OVERFLOW
DB_POOL_RECYCLE_SECONDS = db_cfg.DB_POOL_RECYCLE_SECONDS
DB_POOL_SIZE = db_cfg.DB_POOL_SIZE
DB_POOL_TIMEOUT_SECONDS = db_cfg.DB_POOL_TIMEOUT_SECONDS
DB_SLOW_QUERY_LOG_THRESHOLD_MS = db_cfg.DB_SLOW_QUERY_LOG_THRESHOLD_MS
ENABLE_DB_QUERY_TIMING = db_cfg.ENABLE_DB_QUERY_TIMING
IDEMPOTENCY_TTL_SECONDS = db_cfg.IDEMPOTENCY_TTL_SECONDS

# Security section
WEBSITE_URL = sec_cfg.WEBSITE_URL
SESSION_COOKIE_SECURE = sec_cfg.SESSION_COOKIE_SECURE
SESSION_COOKIE_SAMESITE = sec_cfg.SESSION_COOKIE_SAMESITE
PARTICIPANT_SESSION_COOKIE_NAME = sec_cfg.PARTICIPANT_SESSION_COOKIE_NAME
PARTICIPANT_SESSION_STALE_TTL_SECONDS = sec_cfg.PARTICIPANT_SESSION_STALE_TTL_SECONDS
PARTICIPANT_PUBLIC_COOKIE_NAME = sec_cfg.PARTICIPANT_PUBLIC_COOKIE_NAME
TURNSTILE_ENABLED = sec_cfg.TURNSTILE_ENABLED
TURNSTILE_SECRET_KEY = sec_cfg.TURNSTILE_SECRET_KEY
TURNSTILE_VERIFY_URL = sec_cfg.TURNSTILE_VERIFY_URL
TURNSTILE_TIMEOUT_SECONDS = sec_cfg.TURNSTILE_TIMEOUT_SECONDS
SECRET_KEY = sec_cfg.SECRET_KEY
IP_HASH_SALT = sec_cfg.IP_HASH_SALT
CORS_ORIGINS = sec_cfg.CORS_ORIGINS
CORS_SUPPORTS_CREDENTIALS = sec_cfg.CORS_SUPPORTS_CREDENTIALS
TRUST_PROXY_HEADERS = sec_cfg.TRUST_PROXY_HEADERS
RATELIMIT_STORAGE_URI = sec_cfg.RATELIMIT_STORAGE_URI
SECURITY_HSTS_ENABLED = sec_cfg.SECURITY_HSTS_ENABLED
SECURITY_HSTS_MAX_AGE = sec_cfg.SECURITY_HSTS_MAX_AGE
SECURITY_HSTS_INCLUDE_SUBDOMAINS = sec_cfg.SECURITY_HSTS_INCLUDE_SUBDOMAINS
SECURITY_HSTS_PRELOAD = sec_cfg.SECURITY_HSTS_PRELOAD
SECURITY_FRAME_OPTIONS = sec_cfg.SECURITY_FRAME_OPTIONS
SECURITY_REFERRER_POLICY = sec_cfg.SECURITY_REFERRER_POLICY
SECURITY_PERMISSIONS_POLICY = sec_cfg.SECURITY_PERMISSIONS_POLICY
SECURITY_CONTENT_TYPE_OPTIONS = sec_cfg.SECURITY_CONTENT_TYPE_OPTIONS
SECURITY_XSS_PROTECTION = sec_cfg.SECURITY_XSS_PROTECTION

# Survey section
MIN_WORD_COUNT = survey_cfg.MIN_WORD_COUNT
MIN_DESCRIPTION_LENGTH = survey_cfg.MIN_DESCRIPTION_LENGTH
MAX_DESCRIPTION_LENGTH = survey_cfg.MAX_DESCRIPTION_LENGTH
MIN_FEEDBACK_LENGTH = survey_cfg.MIN_FEEDBACK_LENGTH
MAX_FEEDBACK_LENGTH = survey_cfg.MAX_FEEDBACK_LENGTH
MIN_RATING = survey_cfg.MIN_RATING
MAX_RATING = survey_cfg.MAX_RATING
TOO_FAST_SECONDS = survey_cfg.TOO_FAST_SECONDS
TOO_FAST_ATTENTION_BASE_SECONDS = survey_cfg.TOO_FAST_ATTENTION_BASE_SECONDS
TOO_FAST_SURVEY_BASE_SECONDS = survey_cfg.TOO_FAST_SURVEY_BASE_SECONDS
TOO_FAST_ATTENTION_MAX_THRESHOLD_SECONDS = survey_cfg.TOO_FAST_ATTENTION_MAX_THRESHOLD_SECONDS
TOO_FAST_SURVEY_MAX_THRESHOLD_SECONDS = survey_cfg.TOO_FAST_SURVEY_MAX_THRESHOLD_SECONDS
STAGE_STALE_TIMEOUT_SECONDS = survey_cfg.STAGE_STALE_TIMEOUT_SECONDS
ATTENTION_FLAG_THRESHOLD = survey_cfg.ATTENTION_FLAG_THRESHOLD
ATTENTION_FLAG_MIN_CHECKS = survey_cfg.ATTENTION_FLAG_MIN_CHECKS
ATTENTION_HARD_FLAG_CONSEC_FAILS = survey_cfg.ATTENTION_HARD_FLAG_CONSEC_FAILS
ATTENTION_MIN_DISTINCT_WORDS = survey_cfg.ATTENTION_MIN_DISTINCT_WORDS
ATTENTION_MIN_CHAR_LENGTH = survey_cfg.ATTENTION_MIN_CHAR_LENGTH
ATTENTION_MIN_RECALL = survey_cfg.ATTENTION_MIN_RECALL
IMAGE_BATCH_SIZE_ATTENTION = survey_cfg.IMAGE_BATCH_SIZE_ATTENTION
IMAGE_BATCH_SIZE_SURVEY = survey_cfg.IMAGE_BATCH_SIZE_SURVEY
IMAGE_DELIVERY_FAILURE_WINDOW_SECONDS = survey_cfg.IMAGE_DELIVERY_FAILURE_WINDOW_SECONDS
IMAGE_DELIVERY_FAILURE_QUARANTINE_THRESHOLD = survey_cfg.IMAGE_DELIVERY_FAILURE_QUARANTINE_THRESHOLD
IMAGE_DELIVERY_QUARANTINE_SECONDS = survey_cfg.IMAGE_DELIVERY_QUARANTINE_SECONDS

# Observability section
LOG_LEVEL = obs_cfg.LOG_LEVEL
LOGGING_AUTO_CONFIG = obs_cfg.LOGGING_AUTO_CONFIG
SUPPRESS_ACCESS_LOGS = obs_cfg.SUPPRESS_ACCESS_LOGS
API_LATENCY_SLO_MS = obs_cfg.API_LATENCY_SLO_MS
ENABLE_DEVICE_FINGERPRINTING = obs_cfg.ENABLE_DEVICE_FINGERPRINTING
ENABLE_AUDIT_LOGGING = obs_cfg.ENABLE_AUDIT_LOGGING
ENABLE_ERROR_LOGGING = obs_cfg.ENABLE_ERROR_LOGGING
ENABLE_REQUEST_DB_OBSERVABILITY = obs_cfg.ENABLE_REQUEST_DB_OBSERVABILITY
DEVICE_FINGERPRINT_SALTS = obs_cfg.DEVICE_FINGERPRINT_SALTS
APP_PROCESS_ROLE = obs_cfg.APP_PROCESS_ROLE
ENABLE_DURABLE_EVENT_QUEUE = obs_cfg.ENABLE_DURABLE_EVENT_QUEUE
START_DURABLE_EVENT_WORKER = obs_cfg.START_DURABLE_EVENT_WORKER
DURABLE_EVENT_QUEUE_POLL_MS = obs_cfg.DURABLE_EVENT_QUEUE_POLL_MS
DURABLE_EVENT_QUEUE_MAX_ATTEMPTS = obs_cfg.DURABLE_EVENT_QUEUE_MAX_ATTEMPTS
DURABLE_EVENT_QUEUE_BASE_BACKOFF_MS = obs_cfg.DURABLE_EVENT_QUEUE_BASE_BACKOFF_MS
DURABLE_EVENT_QUEUE_MAX_BACKOFF_MS = obs_cfg.DURABLE_EVENT_QUEUE_MAX_BACKOFF_MS
DURABLE_EVENT_QUEUE_MIN_BACKOFF_MS = obs_cfg.DURABLE_EVENT_QUEUE_MIN_BACKOFF_MS
DURABLE_EVENT_QUEUE_IDLE_SLEEP_MS = obs_cfg.DURABLE_EVENT_QUEUE_IDLE_SLEEP_MS
DURABLE_EVENT_QUEUE_BUSY_SLEEP_MS = obs_cfg.DURABLE_EVENT_QUEUE_BUSY_SLEEP_MS
ASYNC_EXECUTOR_WORKERS_EMAIL_OTP = obs_cfg.ASYNC_EXECUTOR_WORKERS_EMAIL_OTP
ASYNC_EXECUTOR_WORKERS_SUBMISSION_POST_COMMIT = obs_cfg.ASYNC_EXECUTOR_WORKERS_SUBMISSION_POST_COMMIT
ASYNC_EXECUTOR_WORKERS_OBSERVABILITY = obs_cfg.ASYNC_EXECUTOR_WORKERS_OBSERVABILITY
EMAIL_OTP_ASYNC_MAX_ATTEMPTS = obs_cfg.EMAIL_OTP_ASYNC_MAX_ATTEMPTS
EMAIL_OTP_ASYNC_BASE_BACKOFF_MS = obs_cfg.EMAIL_OTP_ASYNC_BASE_BACKOFF_MS
EMAIL_OTP_ASYNC_MAX_BACKOFF_MS = obs_cfg.EMAIL_OTP_ASYNC_MAX_BACKOFF_MS
SUBMISSION_POST_COMMIT_ASYNC_MAX_ATTEMPTS = obs_cfg.SUBMISSION_POST_COMMIT_ASYNC_MAX_ATTEMPTS
SUBMISSION_POST_COMMIT_ASYNC_BASE_BACKOFF_MS = obs_cfg.SUBMISSION_POST_COMMIT_ASYNC_BASE_BACKOFF_MS
SUBMISSION_POST_COMMIT_ASYNC_MAX_BACKOFF_MS = obs_cfg.SUBMISSION_POST_COMMIT_ASYNC_MAX_BACKOFF_MS
OBS_ASYNC_MAX_ATTEMPTS = obs_cfg.OBS_ASYNC_MAX_ATTEMPTS
OBS_ASYNC_BASE_BACKOFF_MS = obs_cfg.OBS_ASYNC_BASE_BACKOFF_MS
PORT = obs_cfg.PORT
FLASK_DEBUG = obs_cfg.FLASK_DEBUG
ROOT_RATE_LIMIT = obs_cfg.ROOT_RATE_LIMIT
DOCS_RATE_LIMIT = obs_cfg.DOCS_RATE_LIMIT
HEALTH_RATE_LIMIT = obs_cfg.HEALTH_RATE_LIMIT
PARTICIPANT_CREATE_RATE_LIMIT = obs_cfg.PARTICIPANT_CREATE_RATE_LIMIT
PARTICIPANT_CHECK_RATE_LIMIT = obs_cfg.PARTICIPANT_CHECK_RATE_LIMIT
PARTICIPANT_SESSION_RATE_LIMIT = obs_cfg.PARTICIPANT_SESSION_RATE_LIMIT
IMAGES_RANDOM_RATE_LIMIT = obs_cfg.IMAGES_RANDOM_RATE_LIMIT
CONSENT_RATE_LIMIT = obs_cfg.CONSENT_RATE_LIMIT
SUBMIT_RATE_LIMIT = obs_cfg.SUBMIT_RATE_LIMIT
EMAIL_OTP_REQUEST_RATE_LIMIT = obs_cfg.EMAIL_OTP_REQUEST_RATE_LIMIT
EMAIL_OTP_VERIFY_RATE_LIMIT = obs_cfg.EMAIL_OTP_VERIFY_RATE_LIMIT

# Env helper aliases used below.
int_env = env_cfg.int_env
required_env = env_cfg.required_env
required_int_env = env_cfg.required_int_env
str_env = env_cfg.str_env
validate_url = env_cfg.validate_url

# Email OTP section
EMAIL_OTP_LENGTH = required_int_env("EMAIL_OTP_LENGTH")
EMAIL_OTP_EXPIRY_SECONDS = required_int_env("EMAIL_OTP_EXPIRY_SECONDS")
EMAIL_OTP_MAX_ATTEMPTS = required_int_env("EMAIL_OTP_MAX_ATTEMPTS")
EMAIL_OTP_WEBHOOK_URL = required_env("EMAIL_OTP_WEBHOOK_URL")
EMAIL_OTP_SENDER = required_env("EMAIL_OTP_SENDER")
EMAIL_OTP_SUBJECT = required_env("EMAIL_OTP_SUBJECT")
EMAIL_OTP_HTML_TEMPLATE = required_env("EMAIL_OTP_HTML_TEMPLATE")
EMAIL_OTP_WEBHOOK_TIMEOUT_SECONDS = int_env("EMAIL_OTP_WEBHOOK_TIMEOUT_SECONDS", 5, min_value=1, max_value=30)
EMAIL_OTP_JWT_SECRET = required_env("EMAIL_OTP_JWT_SECRET")
EMAIL_OTP_JWT_TTL_SECONDS = int_env("EMAIL_OTP_JWT_TTL_SECONDS", 3600, min_value=60, max_value=86400)

# Docs section
DOCS_BASE_URL = str_env("DOCS_BASE_URL", WEBSITE_URL)

ERROR_CODES: Dict[str, Dict[str, Any]] = build_error_codes(
    min_description_length=MIN_DESCRIPTION_LENGTH,
    max_description_length=MAX_DESCRIPTION_LENGTH,
    min_feedback_length=MIN_FEEDBACK_LENGTH,
    max_feedback_length=MAX_FEEDBACK_LENGTH,
    min_rating=MIN_RATING,
    max_rating=MAX_RATING,
    min_word_count=MIN_WORD_COUNT,
)


def validate_config() -> None:
    validate_url("WEBSITE_URL", WEBSITE_URL)
    validate_url("EMAIL_OTP_WEBHOOK_URL", EMAIL_OTP_WEBHOOK_URL)
    if TURNSTILE_ENABLED and not TURNSTILE_SECRET_KEY:
        raise ValueError("TURNSTILE_SECRET_KEY is required when TURNSTILE_ENABLED=true")

    if API_LATENCY_SLO_MS <= 0:
        raise ValueError("API_LATENCY_SLO_MS must be > 0")
    if APP_PROCESS_ROLE not in {"web", "worker", "all"}:
        raise ValueError("APP_PROCESS_ROLE must be one of: web, worker, all")

    if ENABLE_DURABLE_EVENT_QUEUE:
        if DURABLE_EVENT_QUEUE_POLL_MS <= 0:
            raise ValueError("DURABLE_EVENT_QUEUE_POLL_MS must be > 0")
        if DURABLE_EVENT_QUEUE_MAX_ATTEMPTS <= 0:
            raise ValueError("DURABLE_EVENT_QUEUE_MAX_ATTEMPTS must be > 0")
        if DURABLE_EVENT_QUEUE_BASE_BACKOFF_MS <= 0:
            raise ValueError("DURABLE_EVENT_QUEUE_BASE_BACKOFF_MS must be > 0")
        if DURABLE_EVENT_QUEUE_MAX_BACKOFF_MS < DURABLE_EVENT_QUEUE_BASE_BACKOFF_MS:
            raise ValueError("DURABLE_EVENT_QUEUE_MAX_BACKOFF_MS must be >= DURABLE_EVENT_QUEUE_BASE_BACKOFF_MS")
        if DURABLE_EVENT_QUEUE_MIN_BACKOFF_MS > DURABLE_EVENT_QUEUE_BASE_BACKOFF_MS:
            raise ValueError("DURABLE_EVENT_QUEUE_MIN_BACKOFF_MS must be <= DURABLE_EVENT_QUEUE_BASE_BACKOFF_MS")

    if EMAIL_OTP_ASYNC_MAX_ATTEMPTS <= 0 or SUBMISSION_POST_COMMIT_ASYNC_MAX_ATTEMPTS <= 0:
        raise ValueError("Async max attempts must be > 0")
    if EMAIL_OTP_ASYNC_BASE_BACKOFF_MS <= 0 or SUBMISSION_POST_COMMIT_ASYNC_BASE_BACKOFF_MS <= 0:
        raise ValueError("Async base backoff must be > 0")
    if EMAIL_OTP_ASYNC_MAX_BACKOFF_MS < EMAIL_OTP_ASYNC_BASE_BACKOFF_MS:
        raise ValueError("EMAIL_OTP_ASYNC_MAX_BACKOFF_MS must be >= EMAIL_OTP_ASYNC_BASE_BACKOFF_MS")
    if SUBMISSION_POST_COMMIT_ASYNC_MAX_BACKOFF_MS < SUBMISSION_POST_COMMIT_ASYNC_BASE_BACKOFF_MS:
        raise ValueError(
            "SUBMISSION_POST_COMMIT_ASYNC_MAX_BACKOFF_MS must be >= SUBMISSION_POST_COMMIT_ASYNC_BASE_BACKOFF_MS"
        )
    if OBS_ASYNC_MAX_ATTEMPTS <= 0:
        raise ValueError("OBS_ASYNC_MAX_ATTEMPTS must be > 0")
    if OBS_ASYNC_BASE_BACKOFF_MS <= 0:
        raise ValueError("OBS_ASYNC_BASE_BACKOFF_MS must be > 0")

    if ASYNC_EXECUTOR_WORKERS_EMAIL_OTP <= 0:
        raise ValueError("ASYNC_EXECUTOR_WORKERS_EMAIL_OTP must be > 0")
    if ASYNC_EXECUTOR_WORKERS_SUBMISSION_POST_COMMIT <= 0:
        raise ValueError("ASYNC_EXECUTOR_WORKERS_SUBMISSION_POST_COMMIT must be > 0")
    if ASYNC_EXECUTOR_WORKERS_OBSERVABILITY <= 0:
        raise ValueError("ASYNC_EXECUTOR_WORKERS_OBSERVABILITY must be > 0")


validate_config()
