const LANG = "en";

const TEXT = {
  en: {
    "status.pleaseWait": "Please wait",
    "status.loadingApp": "Loading C.O.G.N.I.T.",
    "status.checkingConnectivity": "Checking system connectivity...",
    "status.online": "Online",
    "status.offline": "Offline",
    "status.onlineReady": "All systems connected.",
    "status.offlineSubmissions": "You appear to be offline. Submissions will fail until connectivity is restored.",
    "status.offlineRetry": "We'll retry automatically when you're back online.",
    "status.lastSync": "Last sync: {time}",
    "status.neverSynced": "Last sync: --",
    "step.consent": "Consent",
    "step.details": "Details",
    "step.payment": "Payment",
    "step.survey": "Survey",
    "step.done": "Done",
    "app.subtitle": "Describe each image with as much detail as possible",
    "app.darkModeLight": "Switch to light mode",
    "app.darkModeDark": "Switch to dark mode",
    "app.anotherTabTitle": "Another Tab Is Active",
    "app.anotherTabMessage": "This tab is read-only to prevent multi-tab state conflicts. Continue in the other tab or close it to resume here.",
    "app.reclaimTab": "Try Reclaiming This Tab",
    "app.footerCredit": "Created by Gaurav Kaloliya",
    "toast.dismiss": "Dismiss",
    "common.tryAgainIn": "Try again in {seconds}s.",
    "common.continue": "Continue",
    "common.finish": "Finish",
    "common.back": "Back",
    "common.loading": "Loading...",
    "common.processing": "Processing...",
    "common.submitting": "Submitting...",
    "common.pleaseWait": "Please wait...",
    "common.reload": "Reload",
    "payment.creating": "Creating Payment",
    "payment.pleaseWait": "Please wait...",
    "payment.tryAgainIn": "Try again in {seconds}s.",
    "payment.clearScreenshot": "Remove screenshot",
    "payment.offlineBanner": "You're offline. Payment status may not update until you reconnect.",
    "payment.expiredToast": "Payment session expired. Creating a new one.",
    "payment.expiredRefreshNotice": "Previous payment session expired. A new session has been created.",
    "payment.restoringNotice": "Restoring your previous payment session...",
    "payment.offlineCreate": "You're offline. Payment will be created once you're back online.",
    "payment.offlineRestart": "You're offline. Payment will be restarted once you're back online.",
    "payment.offlineVerify": "You're offline. Verification will start once you're back online.",
    "payment.createTimeout": "Payment creation timed out. Please retry.",
    "payment.documentTitle": "Payment - C.O.G.N.I.T.",
    "payment.leaveBlocked": "Action in progress. Please wait for completion before leaving this page.",
    "payment.fileTooLarge": "File size is {actual}MB. Max allowed is {max}MB.",
    "payment.panelUnavailableTitle": "Payment panel unavailable",
    "payment.panelUnavailableMessage": "{error} You can retry in the same session or create a fresh payment panel.",
    "payment.expiredSubtitle": "Your payment session has timed out",
    "payment.expiredTitle": "Payment Expired",
    "payment.refreshTitle": "Payment session needs refresh",
    "payment.refreshMessage": "No active payment data was found. Reload to create a fresh payment session.",
    "payment.reload": "Reload Payment",
    "payment.previousExpired": "Payment session has expired. Tap Retry to create a new payment session.",
    "payment.expiredShort": "Expired",
    "payment.verifyTitle": "Payment Verification Failed",
    "payment.verifySubtitle": "We could not verify your payment screenshot",
    "payment.verificationIssues": "Verification issues:",
    "payment.payWithUpi": "Pay with UPI",
    "payment.scanVerify": "Scan & Verify Payment",
    "payment.scanQr": "Scan QR Code",
    "payment.qrAlt": "Payment QR Code",
    "payment.scanAnyApp": "Scan with any UPI app to pay {amount}",
    "payment.payWithApp": "Pay {amount} with UPI",
    "payment.pendingBadge": "Payment pending — upload screenshot after paying",
    "payment.instructionsTitle": "Important Instructions",
    "payment.instructionsUseAmount": "Pay exactly {amount} using a UPI app",
    "payment.instructionsSupportedApps": "Use only: Google Pay, Paytm, or BHIM",
    "payment.instructionsTakeScreenshot": "Take a screenshot immediately after payment",
    "payment.instructionsUpload": "Upload the screenshot below to verify",
    "payment.instructionsExpiresIn": "Payment session expires in {time}",
    "payment.uploadTitle": "Upload Payment Screenshot",
    "payment.uploadIntro": "After completing the payment, upload a screenshot from Google Pay, Paytm, or BHIM.",
    "payment.clickToUpload": "Click to upload payment screenshot",
    "payment.noImageSelected": "No image selected",
    "payment.sizeLabel": "Size:",
    "payment.typeLabel": "Type:",
    "payment.typeUnknown": "Unknown",
    "payment.allowedFormats": "Allowed formats: JPG, JPEG, PNG, WEBP | Max: {size}MB",
    "payment.checklistTitle": "Quick checklist",
    "payment.checklistStatus": "Payment status is visible",
    "payment.checklistRecipient": "Recipient shows COGNIT / Gaurav",
    "payment.checklistAmount": "Amount shows exactly {amount}",
    "payment.checklistDateTime": "Date and time are clearly readable",
    "payment.keepTabOpen": "Verification usually takes a few seconds. Keep this tab open.",
    "payment.selectImage": "Select Image",
    "payment.confirmPayment": "Confirm Payment",
    "payment.verifyingAction": "Verifying...",
    "payment.preparingTitle": "Preparing payment screen",
    "payment.preparingSubtitle": "Generating secure payment context",
    "payment.cleanDirect": "Clean. Direct. Transparent.",
    "payment.priorityIntro": "Participants who engage more receive higher selection priority.",
    "payment.priorityUnlock": "Unlock Priority Status by:",
    "payment.priorityOutcome": "More contribution -> Higher probability.",
    "payment.rewardDirectUpi": "Direct UPI transfer",
    "payment.rewardProcessed": "Processed within 24-48 hours",
    "payment.rewardNoMinimum": "No minimum withdrawal",
    "payment.continueToPayment": "Continue to Payment",
    "payment.resolutionLow": "Screenshot resolution is too low ({width}x{height}). Minimum is {minWidth}x{minHeight}.",
    "payment.blurry": "Screenshot appears blurry. Please upload a clearer screenshot.",
    "payment.invalidImage": "Unable to read screenshot. Please upload a valid image.",
    "payment.recovery.useSupportedApp": "Use Google Pay, Paytm, or BHIM, and ensure the recipient shows COGNIT.",
    "payment.recovery.exactAmount": "Pay exactly {amount} and upload the success screenshot.",
    "payment.recovery.withinTimer": "Upload the screenshot immediately after payment, within the active timer.",
    "payment.recovery.clearScreenshot": "Upload a clearer screenshot with time and success status fully visible.",
    "payment.recovery.reusedOther": "This screenshot was already used. Complete a fresh {amount} payment and upload a new screenshot.",
    "payment.recovery.reusedSelf": "You already used this screenshot. Do a fresh payment and upload a new screenshot.",
    "payment.recovery.rejectedReuse": "Previously rejected screenshots cannot be reused. Upload a new successful payment screenshot.",
    "payment.recovery.defaultFresh": "Retry with a fresh screenshot that clearly shows app name, amount {amount}, recipient, and success status.",
    "payment.recovery.defaultRetry": "If it still fails, tap Retry to create a new payment session.",
    "payment.verificationFailedTitle": "Payment Verification Failed",
    "payment.verificationFailedSubtitle": "We could not verify your payment screenshot",
    "payment.nextSteps": "Next steps:",
    "payment.howToFix": "How to fix:",
    "payment.verifyingText": "Verifying screenshot and confirming payment...",
    "payment.successConfirm": "Participation confirmed successfully",
    "payment.timeRemaining": "Time remaining: {time}",
    "payment.completeAndUpload": "Complete payment and upload screenshot",
    "payment.loadingQr": "Loading QR...",
    "payment.loadingQrTitle": "Loading QR",
    "payment.loadingQrSubtitle": "Fetching QR code from the server",
    "consent.offlineBanner": "You're offline. Some actions may not work until you reconnect.",
    "consent.offlineSubmit": "You're offline. Consent will be submitted once you're back online.",
    "consent.saved": "Consent recorded successfully",
    "consent.documentTitle": "Consent Form - C.O.G.N.I.T.",
    "consent.savingTitle": "Saving consent",
    "consent.savingSubtitle": "Securing your participation preferences",
    "consent.requiredHint": "Required to continue",
    "consent.readMore": "Read more",
    "consent.readLess": "Read less",
    "survey.loadingNext": "Loading next survey",
    "survey.loadingNextSubtitle": "Selecting the next image and preparing your form",
    "survey.offlineBanner": "You're offline. Progress might not sync until you reconnect.",
    "survey.offlineSubmit": "You're offline. Submission will be sent once you're back online.",
    "survey.imageRestoreFailed": "Unable to restore survey image. Please retry to continue.",
    "survey.saved": "Your response was saved!",
    "survey.attentionTooFast": "Attention check failed: response was too fast. Please read image instructions carefully.",
    "survey.attentionFailed": "Attention check failed: please follow the special instructions shown in the image.",
    "survey.attentionHardFlag": "Multiple attention failures detected. Please slow down and answer carefully.",
    "survey.feedOffline": "You're offline. Loading the next survey may fail.",
    "survey.feedOfflineContinue": "You're offline. We'll continue once you're back online.",
    "survey.feedLoadFailed": "Failed to load the next survey image. Please retry.",
    "survey.feedLoadFailedWithHint": "{error} Check connection and tap retry.",
    "survey.feedComplete": "Survey Complete",
    "survey.feedCompleteMessage": "You have completed {count} survey{suffix}. Continue for more or finish now.",
    "survey.continue": "Continue Survey",
    "survey.loading": "Loading...",
    "survey.unableLoadNext": "Unable to load next survey",
    "survey.guidanceTitle": "What you can do next",
    "survey.guidanceCheckConnection": "Check your connection and try again.",
    "survey.guidanceContinueLater": "You can finish later from the same device.",
    "survey.guidanceSupport": "If this keeps happening, contact support.",
    "survey.minimumMet": "Minimum met",
    "survey.priorityMet": "Priority met",
    "survey.retryShort": "Retry",
    "survey.retryingShort": "Retrying...",
    "survey.retryIn": "Retry in {seconds}s",
    "survey.canvasSubtitle": "Preparing your survey canvas",
    "survey.imageLoadFailed": "Image load failed",
    "survey.promptAlt": "Prompt",
    "survey.resetZoom": "Reset zoom",
    "survey.zoom": "Zoom",
    "survey.timeElapsed": "Time: {seconds}s",
    "survey.stepLabel": "Survey {current} of {total}",
    "survey.descriptionLabel": "Description",
    "survey.descriptionPlaceholder": "Describe what you see...",
    "survey.wordsChars": "Words {words} | Chars {chars}/{max}",
    "survey.wordsMin": "Words: {words} / Min {min}",
    "survey.minimumWords": "Minimum: {min} words",
    "survey.wordsRemaining": "{remaining} words remaining to reach minimum",
    "survey.wordsGood": "Minimum word target reached",
    "survey.priorityWords": "Priority target: {target}+ words",
    "survey.priorityReachedDesc": "Description target reached for priority queue consideration.",
    "survey.priorityRemainingDesc": "Write {remaining} more words to reach priority level.",
    "survey.ratingLabel": "Image rating",
    "survey.ratingLow": "Very Low",
    "survey.ratingHigh": "Very High",
    "survey.commentsLabel": "Comments",
    "survey.commentsPlaceholder": "Share any additional notes...",
    "survey.charsCount": "Chars {count}/{max}",
    "survey.feedbackMin": "Characters: {count} / Min 4",
    "survey.feedbackMinimum": "Minimum: 4 characters",
    "survey.feedbackRemainingMin": "{remaining} characters remaining to reach minimum",
    "survey.feedbackGood": "Minimum feedback length reached",
    "survey.feedbackPriority": "Priority target: {target}+ characters",
    "survey.feedbackTargetTitle": "Priority feedback target: {target}+ characters",
    "survey.feedbackReached": "Feedback target reached for stronger priority profile.",
    "survey.feedbackRemaining": "Add {remaining} more characters to strengthen priority chances.",
    "survey.submit": "Submit",
    "survey.submitBusy": "Submitting...",
    "survey.submitLocked": "Please wait...",
    "user.offlineBanner": "You're offline. Submissions may fail until you reconnect.",
    "user.offlineSubmit": "You're offline. Details will be submitted once you're back online.",
    "user.optionsLoadingTitle": "Loading options",
    "user.optionsLoadingSubtitle": "Fetching available gender and language options",
    "user.detailsSaved": "Details submitted successfully",
    "user.documentTitle": "User Details - C.O.G.N.I.T.",
    "user.loadingTitle": "Saving participant details",
    "user.loadingSubtitle": "Validating identity and availability checks",
    "user.locationDetecting": "Detecting your location",
    "user.pageTitle": "Participant Information",
    "user.pageSubtitle": "Provide your details to participate in the C.O.G.N.I.T. research survey.",
    "user.username": "Username",
    "user.usernamePlaceholder": "Enter your username",
    "user.usernameHint": "Minimum {min} characters, letters/numbers/underscore",
    "user.usernameHintOk": "Username length looks good",
    "user.email": "Email",
    "user.emailPlaceholder": "yourname@gmail.com",
    "user.emailDomains": "gmail.com|outlook.com|hotmail.com|icloud.com",
    "user.emailHint": "Use a valid email format",
    "user.phone": "Phone Number",
    "user.phonePlaceholder": "10-digit Indian mobile number",
    "user.phoneCount": "Digits: {count}/10",
    "user.phoneHint": "Enter a valid 10-digit Indian mobile number",
    "user.gender": "Gender",
    "user.genderPlaceholder": "Select gender",
    "user.genderMale": "Male",
    "user.genderFemale": "Female",
    "user.genderNonBinary": "Non-binary",
    "user.genderPreferNo": "Prefer not to say",
    "user.genderOther": "Other",
    "user.age": "Age",
    "user.ageHint": "Age must be between {min} and {max}",
    "user.ageRange": "Range: {min}-{max}",
    "user.ageValue": "{value}",
    "user.location": "Place/Location",
    "user.locationPlaceholderDetecting": "Detecting your location...",
    "user.locationPlaceholderManual": "Enter your location manually",
    "user.locationPlaceholderAuto": "Auto-detected location",
    "user.locationHint": "Minimum {min} characters",
    "user.locationPermissionRequired": "Enable location permission to submit.",
    "user.locationFallback": "Location auto-detect failed. Enter your location manually.",
    "user.locationRequesting": "Requesting location access...",
    "user.locationRetrying": "Retrying location with higher accuracy...",
    "user.locationDetected": "Location detected.",
    "user.locationPermissionDenied": "Location permission denied. Enter manually.",
    "user.enableLocation": "Enable Location Permission",
    "user.language": "Native Language",
    "user.languagePlaceholder": "Select native language",
    "user.priorExperience": "Prior Experience",
    "user.priorExperiencePlaceholder": "Select prior experience",
    "user.checking": "Checking...",
    "finish.offlineBanner": "You're offline. Reward updates may not load until you reconnect.",
    "finish.documentTitle": "Thank You - C.O.G.N.I.T.",
    "finish.loadingTitle": "Finalizing your session",
    "finish.loadingSubtitle": "Wrapping up rewards and completion state",
    "finish.loadingRewardsTitle": "Loading reward details",
    "finish.loadingRewardsSubtitle": "Fetching your participation summary",
    "finish.thankYouTitle": "Thank you for completing the C.O.G.N.I.T. survey",
    "finish.pageSubtitle": "You have completed {count} survey{suffix}! Your responses have been recorded.",
    "finish.congrats": "Congratulations!",
    "finish.thanks": "Thank You for Participating",
    "finish.winnerMessage": "You've been selected as a reward winner. Your reward will be processed shortly.",
    "finish.responsesRecorded": "Your responses were recorded successfully and help improve image-text research quality.",
    "finish.rewardHeading": "About the Reward Program",
    "finish.finishButton": "Finish",
    "error.recoveringTitle": "Recovering application state",
    "error.recoveringSubtitle": "Resetting to consent step",
    "error.title": "Something went wrong",
    "error.details": "Error Details",
    "notFound.title": "Page Not Found",
    "notFound.message": "The page you are looking for does not exist or has moved.",
    "notFound.action": "Go Home",
    "service.retryingTitle": "Retrying service health check",
    "service.retryingSubtitle": "Reconnecting to backend services",
    "service.title": "Service Unavailable",
    "service.tipCheckConnection": "Check your internet connection",
    "service.tipRefresh": "Refresh the page and try again",
    "service.tipWait": "Wait a few minutes and retry if the issue persists",
    "service.tipContact": "Contact support if the problem continues",
    "survey.loadingImage": "Loading image...",
    "survey.retrying": "Retrying...",
    "survey.retry": "Retry",
    "draft.restored": "Draft restored from your last session.",
    "autosave.saved": "Autosaved",
    "autosave.savedAt": "Saved at {time}",
    "autosave.pending": "Autosave pending",
    "autosave.saving": "Saving...",
    "autosave.failed": "Autosave failed. We'll retry when possible.",
    "common.backToTop": "Back to top",
    "step.scrollHint": "Swipe to see all steps",
    "survey.submitShortcut": "Tip: Press Ctrl+Enter (Cmd+Enter on Mac) to submit.",
    "survey.autosave": "Your response is auto-saved in this tab."
  }
};

export function uiText(key, params = {}) {
  const pack = TEXT[LANG] || TEXT.en;
  const fallback = TEXT.en[key] || key;
  let value = pack[key] || fallback;
  Object.keys(params).forEach((k) => {
    value = value.replace(`{${k}}`, String(params[k]));
  });
  return value;
}
