const LANG = "en";

const TEXT = {
  en: {
    "status.loadingApp": "Loading C.O.G.N.I.T.",
    "status.checkingConnectivity": "Checking system connectivity...",
    "status.online": "Online",
    "status.offline": "Offline",
    "status.onlineReady": "All systems connected.",
    "status.offlineSubmissions": "You appear to be offline. Submissions will fail until connectivity is restored.",
    "status.lastSync": "Last sync: {time}",
    "status.neverSynced": "Last sync: --",
    "app.brand": "C.O.G.N.I.T.",
    "step.consent": "Consent",
    "step.details": "Details",
    "step.payment": "Payment",
    "step.survey": "Survey",
    "step.done": "Done",
    "app.subtitle": "Describe each image with as much detail as possible",
    "app.darkModeLight": "Switch to light mode",
    "app.darkModeDark": "Switch to dark mode",
    "app.storageUnavailable": "Storage is unavailable in this browser. Progress may reset on refresh.",
    "app.sessionExpired": "Your session expired due to inactivity. Please continue.",
    "app.anotherTabTitle": "This session is open in another tab",
    "app.anotherTabMessage": "Looks like C.O.G.N.I.T. is already open in another tab or window. To keep your progress safe, this tab is read-only. Switch to the other tab, or close it and then return here to continue.",
    "app.reclaimTab": "Use This Tab Instead",
    "app.footerCredit": "C.O.G.N.I.T",
    "illustration.dogAriaLabel": "Cute full body dog illustration",
    "app.rateLimitDefault": "Too many requests. Please slow down and try again.",
    "app.maintenanceDefault": "Website is under maintenance. Please try again later.",
    "toast.dismiss": "Dismiss",
    "common.tryAgainIn": "Try again in {seconds}s.",
    "common.continue": "Continue",
    "common.finish": "Finish",
    "common.loading": "Loading...",
    "common.processing": "Processing...",
    "common.submitting": "Submitting...",
    "common.pleaseWait": "Please wait...",
    "common.reload": "Reload",
    "common.inrAmount": "₹{amount}",
    "common.progress": "Progress",
    "payment.creating": "Creating Payment",
    "payment.pleaseWait": "Please wait...",
    "payment.clearScreenshot": "Remove screenshot",
    "payment.offlineBanner": "You're offline. Payment status may not update until you reconnect.",
    "payment.expiredToast": "Payment session expired. Creating a new one.",
    "payment.expiredRefreshNotice": "Previous payment session expired. A new session has been created.",
    "payment.restoringNotice": "Restoring your previous payment session...",
    "payment.offlineCreate": "You're offline. Payment will be created once you're back online.",
    "payment.offlineRestart": "You're offline. Payment will be restarted once you're back online.",
    "payment.offlineVerify": "You're offline. Verification will start once you're back online.",
    "payment.createTimeout": "Payment creation timed out. Please retry.",
    "payment.documentTitle": "Payment - C.O.G.N.I.T.",
    "payment.leaveBlocked": "Action in progress. Please wait for completion before leaving this page.",
    "payment.fileTooLarge": "File size is {actual}MB. Max allowed is {max}MB.",
    "payment.panelUnavailableTitle": "Payment panel unavailable",
    "payment.panelUnavailableMessage": "{error} You can retry in the same session or create a fresh payment panel.",
    "payment.expiredHeading": "Payment expired",
    "payment.previousExpired": "Payment session has expired. Tap Retry to create a new payment session.",
    "payment.expiredShort": "Expired",
    "payment.verifyTitle": "Payment Verification Failed",
    "payment.verifySubtitle": "We could not verify your payment screenshot",
    "payment.verificationIssues": "Verification issues:",
    "payment.nextStepsTitle": "Next steps:",
    "payment.howToFixTitle": "How to fix:",
    "payment.payWithUpi": "Pay with UPI",
    "payment.scanVerify": "Scan & Verify Payment",
    "payment.scanQr": "Scan QR Code",
    "payment.qrAlt": "Payment QR Code",
    "payment.scanAnyApp": "Scan with any UPI app to pay {amount}",
    "payment.payWithApp": "Pay {amount} with UPI",
    "payment.pendingBadge": "Payment pending — upload screenshot after paying",
    "payment.previewAlt": "Payment screenshot preview",
    "payment.instructionsTitle": "Important Instructions",
    "payment.instructionsUseAmount": "Pay exactly {amount} using a UPI app",
    "payment.instructionsSupportedApps": "Use only: Google Pay, Paytm, or BHIM",
    "payment.instructionsTakeScreenshot": "Take a screenshot immediately after payment",
    "payment.instructionsUpload": "Upload the screenshot below to verify",
    "payment.instructionsExpiresIn": "Payment session expires in {time}",
    "payment.uploadTitle": "Upload Payment Screenshot",
    "payment.uploadIntro": "After completing the payment, upload a screenshot from Google Pay, Paytm, or BHIM.",
    "payment.clickToUpload": "Click to upload payment screenshot",
    "payment.noImageSelected": "No image selected",
    "payment.sizeLabel": "Size:",
    "payment.typeLabel": "Type:",
    "payment.typeUnknown": "Unknown",
    "payment.allowedFormats": "Allowed formats: JPG, JPEG, PNG, WEBP | Max: {size}MB",
    "payment.checklistTitle": "Quick checklist",
    "payment.checklistStatus": "Success status is clearly visible (not failed/pending)",
    "payment.checklistRecipient": "Recipient shows COGNIT / Gaurav",
    "payment.checklistAmount": "Amount shows exactly {amount}",
    "payment.checklistDateTime": "Date and time are clearly readable",
    "payment.keepTabOpen": "Verification usually takes a few seconds. Keep this tab open.",
    "payment.selectImage": "Select Image",
    "payment.confirmPayment": "Confirm Payment",
    "payment.verifyingAction": "Verifying...",
    "payment.preparingTitle": "Preparing payment screen",
    "payment.preparingSubtitle": "Generating secure payment context",
    "payment.cleanDirect": "Clean. Direct. Transparent.",
    "payment.contentTitle": "Win {reward}",
    "payment.contentSubtitle": "Participate → Get a chance to receive {reward}",
    "payment.contentTagline": "{fee} entry. Real reward.",
    "payment.contentParticipationHeading": "{fee} Participation",
    "payment.contentParticipationIntro": "Your {fee} entry enters you into the reward pool.",
    "payment.contentParticipationBullet1": "Entry fee: {fee}",
    "payment.contentParticipationBullet2": "Chance to win {reward} via UPI",
    "payment.contentHowItWorksHeading": "How It Works",
    "payment.contentStep1": "Pay {fee} via UPI",
    "payment.contentStep2": "Upload payment screenshot",
    "payment.contentStep3": "Your entry is added to the pool",
    "payment.contentStep4": "Winners receive {reward} (24–48 hours)",
    "payment.priorityIntro": "Participants who engage more receive higher selection priority.",
    "payment.priorityUnlock": "Unlock Priority Status by:",
    "payment.priorityOutcome": "More contribution -> Higher probability.",
    "payment.contentIncreaseOddsHeading": "Increase Your Odds",
    "payment.contentChecklist1": "Writing {words}+ total words",
    "payment.contentChecklist2": "Completing {rounds}+ rounds",
    "payment.contentChecklist3": "Submitting {submissions}+ total submissions",
    "payment.contentRewardDetailsHeading": "Reward Details",
    "payment.contentRewardDetail1": "{reward} per selected entry",
    "payment.rewardDirectUpi": "Direct UPI transfer",
    "payment.rewardProcessed": "Processed within 24-48 hours",
    "payment.rewardNoMinimum": "No minimum withdrawal",
    "payment.continueToPayment": "Continue to Payment",
    "payment.resolutionLow": "Screenshot resolution is too low ({width}x{height}). Minimum is {minWidth}x{minHeight}.",
    "payment.blurry": "Screenshot appears blurry. Please upload a clearer screenshot.",
    "payment.invalidImage": "Unable to read screenshot. Please upload a valid image.",
    "payment.recovery.useSupportedApp": "Use Google Pay, Paytm, or BHIM, and ensure the recipient shows COGNIT.",
    "payment.recovery.exactAmount": "Pay exactly {amount} and upload the success screenshot.",
    "payment.recovery.withinTimer": "Upload the screenshot immediately after payment, within the active timer.",
    "payment.recovery.clearScreenshot": "Upload a clearer screenshot with time and success status fully visible.",
    "payment.recovery.successStatus": "Make sure the screenshot clearly shows a successful payment status.",
    "payment.recovery.failureStatus": "The screenshot looks failed/pending. Complete a successful payment and upload that screenshot.",
    "payment.recovery.reusedOther": "This screenshot was already used. Complete a fresh {amount} payment and upload a new screenshot.",
    "payment.recovery.reusedSelf": "You already used this screenshot. Do a fresh payment and upload a new screenshot.",
    "payment.recovery.rejectedReuse": "Previously rejected screenshots cannot be reused. Upload a new successful payment screenshot.",
    "payment.recovery.defaultFresh": "Retry with a fresh screenshot that clearly shows app name, amount {amount}, recipient, and success status.",
    "payment.recovery.defaultRetry": "If it still fails, tap Retry to create a new payment session.",
    "consent.estimatedDurationPrefix": "Estimated duration:",
    "consent.entryFeeLabel": "Entry fee:",
    "consent.rewardDrawLabel": "Reward draw:",
    "consent.rewardDrawMessage": "Randomly selected participants receive {reward} via UPI (typically within 24-48 hours)",
    "consent.emailLabel": "Email:",
    "consent.contactEmailValue": "research@cognit.online",
    "payment.nextSteps": "Next steps:",
    "payment.howToFix": "How to fix:",
    "payment.verifyingText": "Verifying screenshot and confirming payment...",
    "payment.successConfirm": "Participation confirmed successfully",
    "payment.timeRemaining": "Time remaining: {time}",
    "payment.completeAndUpload": "Complete payment and upload screenshot",
    "payment.loadingQr": "Loading QR...",
    "payment.loadingQrTitle": "Loading QR",
    "payment.loadingQrSubtitle": "Fetching QR code from the server",
    "consent.offlineBanner": "You're offline. Some actions may not work until you reconnect.",
    "consent.offlineSubmit": "You're offline. Consent will be submitted once you're back online.",
    "consent.saved": "Consent recorded successfully",
    "consent.documentTitle": "Consent Form - C.O.G.N.I.T.",
    "consent.savingTitle": "Saving consent",
    "consent.savingSubtitle": "Securing your participation preferences",
    "consent.requiredHint": "Required to continue",
    "consent.readMore": "Read more",
    "consent.readLess": "Read less",
    "consent.contentTitle": "C.O.G.N.I.T. Consent Form for Research Participation",
    "consent.contentSubtitle": "We sincerely appreciate you considering being part of this work.",
    "consent.sectionPurpose": "Purpose of the Study",
    "consent.sectionPurposeP1": "The C.O.G.N.I.T. (Cognitive Network for Image & Text Modeling) project investigates how humans interpret and verbally describe visual scenes. Your descriptions contribute to research on perceptual processes, linguistic expression of visual experience, and cognitive mechanisms of scene understanding.",
    "consent.sectionPurposeP2": "The findings support peer-reviewed cognitive science research and the responsible development of interpretable, multimodal AI systems.",
    "consent.sectionParticipation": "What Participation Involves",
    "consent.sectionParticipationIntro": "If you choose to participate, you will:",
    "consent.sectionParticipationItem1": "Create an account using a supported email provider",
    "consent.sectionParticipationItem2": "Provide minimal demographic information (age group, gender, state/UT, primary language)",
    "consent.sectionParticipationItem3": "Complete a brief practice survey",
    "consent.sectionParticipationItem4": "View a sequence of everyday and abstract images",
    "consent.sectionParticipationItem5": "Write detailed, natural descriptions for each image (minimum 60 words)",
    "consent.sectionParticipationItem6": "Indicate perceived image complexity on a 1-10 scale",
    "consent.sectionParticipationItem7": "Respond to a small number of instruction-verification items designed to ensure attentive participation",
    "consent.sectionParticipationP1": "Estimated duration: 5-10 minutes.",
    "consent.sectionParticipationP2": "You may pause or discontinue at any time. If platform functionality allows, you may resume later.",
    "consent.sectionIntegrity": "Data Quality and Participation Integrity",
    "consent.sectionIntegrityIntro": "To maintain scientific validity:",
    "consent.sectionIntegrityItem1": "The platform uses automated systems to evaluate response completeness, instruction compliance, timing consistency, and response-behavior patterns.",
    "consent.sectionIntegrityItem2": "Some surveys are designed to verify that instructions are being carefully followed.",
    "consent.sectionIntegrityItem3": "Repeated failure to follow instructions or patterns indicating inattentive participation may result in temporary or permanent restriction from continuing the task.",
    "consent.sectionIntegrityItem4": "These quality assessments are conducted algorithmically and are applied uniformly to all participants.",
    "consent.sectionIntegrityItem5": "The exact validation thresholds are not disclosed in order to preserve research integrity.",
    "consent.sectionRights": "Your Rights",
    "consent.sectionRightsP1": "Participation is entirely voluntary.",
    "consent.sectionRightsP2": "You may:",
    "consent.sectionRightsItem1": "Withdraw at any time without penalty",
    "consent.sectionRightsOutro": "Early withdrawal before task completion means you will not be entered into the reward draw.",
    "consent.sectionCompensation": "Compensation Structure",
    "consent.sectionCompensationP1": "Participants demonstrating consistent, attentive, and high-quality responses may receive priority in reward allocation. Quality is assessed using objective behavioral metrics such as response completeness, instruction compliance, and response consistency. Receipt of any reward is not guaranteed.",
    "consent.sectionProtection": "Data Protection and Confidentiality",
    "consent.sectionProtectionIntro": "We collect:",
    "consent.sectionProtectionItem1": "Account identifiers (username, contact information)",
    "consent.sectionProtectionItem2": "Basic demographics (age group, gender, Indian state/UT, primary language)",
    "consent.sectionProtectionItem3": "Image descriptions and complexity ratings",
    "consent.sectionProtectionItem4": "Limited behavioral metadata (response timing, instruction compliance indicators)",
    "consent.sectionProtectionSecondaryIntro": "Safeguards include:",
    "consent.sectionProtectionSecondaryItem1": "Separation of contact information from research data",
    "consent.sectionProtectionSecondaryItem2": "Irreversible cryptographic hashing of IP addresses",
    "consent.sectionProtectionSecondaryItem3": "Storage under randomized research identifiers",
    "consent.sectionProtectionSecondaryItem4": "Encryption in transit and at rest",
    "consent.sectionProtectionSecondaryItem5": "Access restricted to named principal investigators and authorized personnel under strict confidentiality agreements",
    "consent.sectionProtectionSecondaryItem6": "Publication only of fully anonymized, aggregated statistics or de-identified excerpts that cannot be traced to individuals",
    "consent.sectionProtectionOutro": "Your data will be used exclusively for scientific research and ethical AI development. No commercial marketing, profiling, or resale will occur.",
    "consent.sectionEligibility": "Eligibility Requirements",
    "consent.sectionEligibilityIntro": "By proceeding, you confirm that you:",
    "consent.sectionEligibilityItem1": "Are currently located in India",
    "consent.sectionEligibilityItem2": "Are 13 years of age or older",
    "consent.sectionEligibilityItem3": "Have access to a supported email provider",
    "consent.sectionEligibilityItem4": "Are comfortable reading and writing in English",
    "consent.sectionContact": "Contact Information",
    "consent.sectionContactP1": "For questions, concerns, or complaints:",
    "consent.sectionConsent": "Statement of Consent",
    "consent.sectionConsentIntro": "By selecting \"I Consent & Proceed\", you confirm that you:",
    "consent.sectionConsentItem1": "Have carefully read and understood this information",
    "consent.sectionConsentItem2": "Freely and voluntarily agree to participate",
    "consent.sectionConsentItem3": "Understand that automated systems evaluate participation quality",
    "consent.sectionConsentItem4": "Acknowledge that participation may be limited if instruction-verification checks are repeatedly failed",
    "consent.sectionConsentItem5": "Understand that anonymized contributions may appear in scientific publications or conference presentations in aggregated or de-identified form",
    "consent.sectionConsentItem6": "Know you may stop at any time",
    "consent.sectionConsentOutro": "Your thoughtful participation advances scientific understanding of human vision-language interaction and supports the development of more interpretable, equitable AI systems.",
    "consent.actionRequiredTitle": "Action required",
    "consent.checkboxTitle": "I consent to participate in this research",
    "consent.checkboxNote": "I confirm that I have read and understood the consent information above and voluntarily agree to participate.",
    "survey.loadingNext": "Loading next survey",
    "survey.loadingNextSubtitle": "Selecting the next image and preparing your form",
    "survey.offlineBanner": "You're offline. Progress might not sync until you reconnect.",
    "survey.offlineSubmit": "You're offline. Submission will be sent once you're back online.",
    "survey.imageRestoreFailed": "Unable to restore survey image. Please retry to continue.",
    "survey.saved": "Your response was saved!",
    "survey.attentionTooFast": "Attention check failed: response was too fast. Please read image instructions carefully.",
    "survey.attentionFailed": "Attention check failed: please follow the special instructions shown in the image.",
    "survey.attentionHardFlag": "Multiple attention failures detected. Please slow down and answer carefully.",
    "survey.feedOffline": "You're offline. Loading the next survey may fail.",
    "survey.feedOfflineContinue": "You're offline. We'll continue once you're back online.",
    "survey.feedLoadFailed": "Failed to load the next survey image. Please retry.",
    "survey.feedLoadFailedWithHint": "{error} Check connection and tap retry.",
    "survey.feedComplete": "Survey Complete",
    "survey.feedCompleteMessage": "You have completed {count} survey{suffix}. Continue for more or finish now.",
    "survey.feedTip": "Tip: Aim to describe colors, textures, relationships, and any notable objects. Remember to write at least {minWords} words per description.",
    "survey.loading": "Loading...",
    "survey.unableLoadNext": "Unable to load next survey",
    "survey.guidanceTitle": "What you can do next",
    "survey.guidanceCheckConnection": "Check your connection and try again.",
    "survey.guidanceContinueLater": "You can finish later from the same device.",
    "survey.guidanceSupport": "If this keeps happening, contact support.",
    "survey.minimumMet": "Minimum met",
    "survey.priorityMet": "Priority met",
    "survey.canvasSubtitle": "Preparing your survey canvas",
    "survey.imageLoadFailed": "Image load failed",
    "survey.promptAlt": "Prompt",
    "survey.resetZoom": "Reset zoom",
    "survey.zoom": "Zoom",
    "survey.timeElapsed": "Time: {seconds}s",
    "survey.stepLabel": "Survey {current} of {total}",
    "survey.descriptionLabel": "Description",
    "survey.descriptionPlaceholder": "Describe what you see...",
    "survey.wordsChars": "Words {words} | Chars {chars}/{max}",
    "survey.wordsMin": "Words: {words} / Min {min}",
    "survey.minimumWords": "Minimum: {min} words",
    "survey.wordsRemaining": "{remaining} words remaining to reach minimum",
    "survey.wordsGood": "Minimum word target reached",
    "survey.priorityWords": "Priority target: {target}+ words",
    "survey.priorityReachedDesc": "Description target reached for priority queue consideration.",
    "survey.priorityRemainingDesc": "Write {remaining} more words to reach priority level.",
    "survey.ratingLabel": "Image rating",
    "survey.ratingLow": "Very Low",
    "survey.ratingHigh": "Very High",
    "survey.commentsLabel": "Comments",
    "survey.commentsPlaceholder": "Share any additional notes...",
    "survey.charsCount": "Chars {count}/{max}",
    "survey.feedbackMin": "Characters: {count} / Min 4",
    "survey.feedbackMinimum": "Minimum: 4 characters",
    "survey.feedbackRemainingMin": "{remaining} characters remaining to reach minimum",
    "survey.feedbackGood": "Minimum feedback length reached",
    "survey.feedbackPriority": "Priority target: {target}+ characters",
    "survey.feedbackTargetTitle": "Priority feedback target: {target}+ characters",
    "survey.feedbackReached": "Feedback target reached for stronger priority profile.",
    "survey.feedbackRemaining": "Add {remaining} more characters to strengthen priority chances.",
    "survey.submit": "Submit",
    "survey.submitBusy": "Submitting...",
    "survey.submitLocked": "Please wait...",
    "survey.navigationBlocked": "Submission in progress. Please wait before leaving this page.",
    "survey.descriptionNotes": "Strong start. Add one more concrete visual detail.|Nice momentum. Expand with color, position, and context.|Good flow. Mention object relationships to boost clarity.|Great effort. Add scene depth and small visible cues.|You are building quality. Add sequence or action details.|High-value response. Add what stands out most and why.|Excellent pace. Add contrast, count, or spatial references.|Almost priority-ready. Add richer context and precision.|Very close to priority tier. Add one strong final paragraph.|Priority target reached. Keep this detail level for top quality.",
    "survey.feedbackNotes": "Start with one clear thought about the task.|Good start. Add what felt easy or difficult.|Add a practical suggestion to improve the prompt.|Great. Mention whether image quality affected your response.|Helpful feedback. Add one specific improvement idea.|Strong direction. Explain what increased your confidence.|Useful signal. Add an example to make feedback actionable.|Almost priority-ready. Add one concise final insight.|Very close. Add what would make this task smoother.|Priority feedback reached. Clear, detailed, and actionable.",
    "user.offlineBanner": "You're offline. Submissions may fail until you reconnect.",
    "user.offlineSubmit": "You're offline. Details will be submitted once you're back online.",
    "user.detailsSaved": "Details submitted successfully",
    "email.requesting": "Sending verification code...",
    "email.verifying": "Verifying code...",
    "email.otpLabel": "Verification code",
    "email.otpExpiresIn": "Code expires in {time}",
    "email.otpExpired": "Code expired. Request a new one.",
    "email.sendAgain": "Resend code",
    "email.sentToast": "Verification code sent",
    "email.verifiedToast": "Email verified successfully",
    "email.offlineBanner": "You're offline. Verification will resume when you're back online.",
    "email.offlineRequest": "You're offline. We'll send the code once you're back online.",
    "email.resendIn": "Resend in {seconds}s",
    "user.documentTitle": "User Details - C.O.G.N.I.T.",
    "user.pageTitle": "Participant Information",
    "user.pageSubtitle": "Provide your details to participate in the C.O.G.N.I.T. research survey.",
    "user.username": "Username",
    "user.usernamePlaceholder": "Enter your username",
    "user.usernameHint": "Minimum {min} characters, letters/numbers/underscore",
    "user.email": "Email",
    "user.emailDomains": "gmail.com|outlook.com|hotmail.com|icloud.com",
    "user.emailDefaultDomain": "gmail.com",
    "user.emailGhostPrefix": "yourname@",
    "user.emailHint": "Use a valid email format",
    "user.gender": "Gender",
    "user.genderPlaceholder": "Select gender",
    "user.age": "Age",
    "user.agePlaceholderRange": "Age ({min}-{max})",
    "user.ageHint": "Age must be between {min} and {max}",
    "user.location": "Place/Location",
    "user.locationPlaceholderDetecting": "Detecting your location...",
    "user.locationPlaceholderManual": "Enter your location manually",
    "user.locationPlaceholderAuto": "Auto-detected location",
    "user.locationHint": "Minimum {min} characters",
    "user.locationPermissionRequired": "Enable location permission to submit.",
    "user.locationFallback": "Location auto-detect failed. Enter your location manually.",
    "user.locationRequesting": "Requesting location access...",
    "user.locationRetrying": "Retrying location with higher accuracy...",
    "user.locationDetected": "Location detected.",
    "user.locationPermissionDenied": "Location permission denied. Enter manually.",
    "user.locationPermissionHelp": "Enable location in your browser/app settings, then tap Enable Location again.",
    "user.enableLocation": "Enable Location Permission",
    "user.language": "Native Language",
    "user.languagePlaceholder": "Select native language",
    "user.priorExperience": "Prior Experience",
    "user.priorExperiencePlaceholder": "Select prior experience",
    "user.checking": "Checking...",
    "finish.offlineBanner": "You're offline. Reward updates may not load until you reconnect.",
    "finish.offlineFinishMessage": "Connect to the internet to finish.",
    "finish.documentTitle": "Thank You - C.O.G.N.I.T.",
    "finish.thankYouTitle": "Thank you for completing the C.O.G.N.I.T. survey",
    "finish.pageSubtitle": "You have completed {count} survey{suffix}! Your responses have been recorded.",
    "finish.thanks": "Thank You for Participating",
    "finish.responsesRecorded": "Your responses were recorded successfully and help improve image-text research quality.",
    "finish.rewardHeading": "About the Reward Program",
    "finish.rewardBullet1": "Participants are randomly selected to receive {amount} rewards.",
    "finish.rewardBullet2": "Active participants who write detailed descriptions get added to a priority list.",
    "finish.rewardBullet3": "Priority participants have higher chances of being selected.",
    "finish.rewardBullet4": "Rewards are sent via UPI transfer within 24-48 hours.",
    "finish.rewardBullet5": "If you're selected, you'll receive an email/SMS with payment confirmation.",
    "finish.debrief": "Debrief: C.O.G.N.I.T. (Cognitive Network for Image & Text Modeling) advances our understanding of how humans describe visual content and how AI can better model this cognitive process. Your responses contribute to improving image-text understanding and generation systems.",
    "finish.finishButton": "Finish",
    "error.recoveringTitle": "Recovering application state",
    "error.recoveringSubtitle": "Resetting to consent step",
    "error.title": "Something went wrong",
    "error.details": "Error Details",
    "rateLimit.title": "Too Many Requests",
    "rateLimit.recoveringTitle": "Waiting to retry",
    "rateLimit.recoveringSubtitle": "Giving the server a moment…",
    "maintenance.title": "Website under maintenance",
    "maintenance.recoveringTitle": "Waiting to retry",
    "maintenance.recoveringSubtitle": "Giving the server a moment…",
    "notFound.title": "Page Not Found",
    "notFound.message": "The page you are looking for does not exist or has moved.",
    "notFound.action": "Go Home",
    "service.retryingTitle": "Retrying service health check",
    "service.retryingSubtitle": "Reconnecting to backend services",
    "service.title": "Service Unavailable",
    "service.tipsTitle": "What you can try:",
    "service.tipCheckConnection": "Check your internet connection",
    "service.tipRefresh": "Refresh the page and try again",
    "service.tipWait": "Wait a few minutes and retry if the issue persists",
    "service.tipContact": "Contact support if the problem continues",
    "publicId.missing": "Account not found. Please register first.",
    "skeleton.defaultTitle": "Loading...",
    "skeleton.defaultSubtitle": "Preparing your experience",
    "turnstile.unavailableBrowser": "Turnstile unavailable in non-browser context",
    "turnstile.loadFailed": "Failed to load Turnstile script",
    "turnstile.siteKeyMissing": "Turnstile site key is missing",
    "turnstile.loadTimedOut": "Turnstile load timed out",
    "turnstile.notInitialized": "Turnstile not initialized",
    "turnstile.executionFailed": "Turnstile execution failed",
    "turnstile.tokenExpired": "Turnstile token expired",
    "turnstile.renderFailed": "Turnstile render failed",
    "turnstile.executionTimedOut": "Turnstile execution timed out",
    "turnstile.unavailable": "Turnstile unavailable",
    "survey.loadingImage": "Loading image...",
    "draft.restored": "Draft restored from your last session.",
    "autosave.failed": "Autosave failed. We'll retry when possible.",
    "common.backToTop": "Back to top",
    "step.scrollHint": "Swipe to see all steps",
    "survey.submitShortcut": "Tip: Press Ctrl+Enter (Cmd+Enter on Mac) to submit."
  }
};

export function uiText(key, params = {}) {
  const pack = TEXT[LANG] || TEXT.en;
  const fallback = TEXT.en[key] || key;
  let value = pack[key] || fallback;
  Object.keys(params).forEach((k) => {
    value = value.replace(`{${k}}`, String(params[k]));
  });
  return value;
}
