"""Centralized backend error catalog."""

from __future__ import annotations

from typing import Any, Dict

ERROR_MESSAGE_TEMPLATES = {
    "IDEMPOTENCY_HEADER_MISSING": "Missing required X-Idempotency-Key header.",
    "IDEMPOTENCY_HEADER_TOO_LONG": "X-Idempotency-Key must be <= 128 characters.",
    "PAYMENT_CREATE_FAILED": "Payment creation failed. Please try again.",
    "PAYMENT_QR_FAILED": "Failed to load payment QR. Please retry.",
    "PAYMENT_UPLOAD_URL_FAILED": "Failed to prepare upload URL. Please try again.",
    "PAYMENT_VERIFY_FAILED": "Payment verification failed. Please try again.",
    "PAYMENT_IMAGE_TOO_LARGE": "The file is too large. Please upload an image smaller than {max_mb}MB.",
    "PAYMENT_SCREENSHOT_SAVE_FAILED": "Failed to save payment screenshot",
    "PAYLOAD_TOO_LARGE": "The file is too large. Please upload an image smaller than {max_mb}MB.",
    "SERVICE_DEGRADED": "Service degraded",
    "INVALID_IMAGE_DATA": "Invalid image data",
}

DETAIL_REASONS = {
    "PAYMENT_IMAGE_TOO_LARGE": "payment_image_too_large",
    "PAYLOAD_TOO_LARGE": "payload_too_large",
    "SESSION_EXPIRED_BEFORE_VERIFY": "session_expired_before_verify",
    "MAX_VERIFY_ATTEMPTS_EXCEEDED": "max_verify_attempts_exceeded",
    "S3_UPLOAD_FAILED": "s3_upload_failed",
}


def build_error_codes(
    *,
    min_description_length: int,
    max_description_length: int,
    min_feedback_length: int,
    max_feedback_length: int,
    min_rating: int,
    max_rating: int,
    min_word_count: int,
) -> Dict[str, Dict[str, Any]]:
    error_codes: Dict[str, Dict[str, Any]] = {
        "SYS_INTERNAL_ERROR": {"code": "SYS_001_0001", "message": "Something went wrong. Please try again.", "status": 500, "category": "SYS"},
        "SYS_DATABASE_ERROR": {"code": "SYS_001_0002", "message": "Database error occurred. Please try again later.", "status": 500, "category": "SYS"},
        "SYS_SERVICE_UNAVAILABLE": {"code": "SYS_001_0003", "message": "Service temporarily unavailable. Please try later.", "status": 503, "category": "SYS"},
        "SYS_CONFIG_ERROR": {"code": "SYS_001_0004", "message": "Configuration error. Please contact support.", "status": 500, "category": "SYS"},
        "DATABASE_ERROR": {"code": "ERR_DATABASE", "message": "An internal error occurred. Please try again later.", "status": 500, "category": "SYS"},
        "INTERNAL_ERROR": {"code": "ERR_INTERNAL", "message": "Something went wrong. Please try again.", "status": 500, "category": "SYS"},
        "RATE_LIMIT_EXCEEDED": {"code": "RATE_001_0001", "message": "Too many attempts. Please wait a moment.", "status": 429, "category": "RATE"},
        "RATE_TOO_MANY_REQUESTS": {"code": "RATE_001_0002", "message": "Rate limit exceeded. Please slow down.", "status": 429, "category": "RATE"},
        "RATE_LIMIT": {"code": "ERR_RATE_LIMIT", "message": "Too many requests. Please slow down.", "status": 429, "category": "RATE"},
        "VAL_MISSING_FIELDS": {"code": "VAL_003_0001", "message": "Please fill in all required fields", "status": 400, "category": "VAL", "field": "general"},
        "VAL_INVALID_FORMAT": {"code": "VAL_003_0002", "message": "Invalid request format", "status": 400, "category": "VAL"},
        "VAL_INVALID_REQUEST_ID": {"code": "VAL_003_0003", "message": "Invalid request ID format", "status": 400, "category": "VAL"},
        "VAL_METHOD_NOT_ALLOWED": {"code": "VAL_003_0007", "message": "HTTP method not allowed for this route", "status": 405, "category": "VAL"},
        "VAL_FILE_TOO_LARGE": {"code": "VAL_003_0005", "message": "The file is too large. Please upload a smaller image.", "status": 413, "category": "VAL", "field": "image_base64"},
        "VAL_USERNAME_INVALID": {"code": "VAL_001_0001", "message": "Username must be at least 2 characters and contain only letters, numbers, and underscores", "status": 400, "category": "VAL", "field": "username"},
        "VAL_EMAIL_INVALID": {"code": "VAL_001_0002", "message": "Please enter a valid email address from Gmail, Outlook, Hotmail, or iCloud", "status": 400, "category": "VAL", "field": "email"},
        "VAL_PHONE_INVALID": {"code": "VAL_001_0003", "message": "Please enter a valid 10-digit Indian mobile number", "status": 400, "category": "VAL", "field": "phone"},
        "VAL_AGE_INVALID": {"code": "VAL_001_0004", "message": "Age must be between 13 and 100", "status": 400, "category": "VAL", "field": "age"},
        "VAL_GENDER_REQUIRED": {"code": "VAL_001_0005", "message": "Please select a gender", "status": 400, "category": "VAL", "field": "gender_code"},
        "VAL_LOCATION_REQUIRED": {"code": "VAL_001_0006", "message": "Please enter your location", "status": 400, "category": "VAL", "field": "location"},
        "VAL_LANGUAGE_REQUIRED": {"code": "VAL_001_0007", "message": "Please select your native language", "status": 400, "category": "VAL", "field": "language_code"},
        "VAL_EXPERIENCE_REQUIRED": {"code": "VAL_001_0008", "message": "Please select your prior experience", "status": 400, "category": "VAL", "field": "prior_experience"},
        "VAL_DESC_LENGTH": {"code": "VAL_002_0001", "message": f"Description must be {min_description_length}-{max_description_length} characters", "status": 400, "category": "VAL", "field": "description"},
        "VAL_DESC_TOO_SHORT": {"code": "VAL_002_0002", "message": f"Description must be at least {min_description_length} characters", "status": 400, "category": "VAL", "field": "description"},
        "VAL_DESC_TOO_LONG": {"code": "VAL_002_0003", "message": f"Description cannot exceed {max_description_length} characters", "status": 400, "category": "VAL", "field": "description"},
        "VAL_WORD_COUNT": {"code": "VAL_002_0004", "message": f"At least {min_word_count} words required", "status": 400, "category": "VAL", "field": "description"},
        "VAL_FEEDBACK_LENGTH": {"code": "VAL_002_0005", "message": f"Feedback must be {min_feedback_length}-{max_feedback_length} characters", "status": 400, "category": "VAL", "field": "feedback"},
        "VAL_FEEDBACK_TOO_SHORT": {"code": "VAL_002_0006", "message": f"Feedback must be at least {min_feedback_length} characters", "status": 400, "category": "VAL", "field": "feedback"},
        "VAL_FEEDBACK_TOO_LONG": {"code": "VAL_002_0007", "message": f"Feedback cannot exceed {max_feedback_length} characters", "status": 400, "category": "VAL", "field": "feedback"},
        "VAL_RATING_INVALID": {"code": "VAL_002_0008", "message": f"Rating must be between {min_rating} and {max_rating}", "status": 400, "category": "VAL", "field": "rating"},
        "VAL_SURVEY_INDEX": {"code": "VAL_002_0011", "message": "Invalid survey index", "status": 400, "category": "VAL", "field": "survey_index"},
        "MISSING_FIELDS": {"code": "ERR_MISSING_FIELDS", "message": "Required fields are missing.", "status": 400, "category": "VAL"},
        "INVALID_FORMAT": {"code": "ERR_INVALID_FORMAT", "message": "Invalid data format.", "status": 400, "category": "VAL"},
        "INVALID_UUID": {"code": "ERR_INVALID_UUID", "message": "Invalid identifier format.", "status": 400, "category": "VAL"},
        "DESCRIPTION_LENGTH": {"code": "ERR_DESC_LENGTH", "message": f"Description must be {min_description_length}-{max_description_length} characters.", "status": 400, "category": "VAL"},
        "FEEDBACK_LENGTH": {"code": "ERR_FEEDBACK_LENGTH", "message": f"Feedback must be {min_feedback_length}-{max_feedback_length} characters.", "status": 400, "category": "VAL"},
        "RATING_INVALID": {"code": "ERR_RATING_INVALID", "message": f"Rating must be between {min_rating} and {max_rating}.", "status": 400, "category": "VAL"},
        "WORD_COUNT": {"code": "ERR_WORD_COUNT", "message": f"At least {min_word_count} words required.", "status": 400, "category": "VAL"},
        "INVALID_IMAGE_ID": {"code": "ERR_INVALID_IMAGE_ID", "message": "Invalid image identifier.", "status": 400, "category": "VAL"},
        "DUP_USERNAME": {"code": "DUP_001_0001", "message": "This username is already taken", "status": 409, "category": "DUP", "field": "username"},
        "DUP_EMAIL": {"code": "DUP_001_0002", "message": "This email is already registered", "status": 409, "category": "DUP", "field": "email"},
        "DUP_PHONE": {"code": "DUP_001_0003", "message": "This phone number is already registered", "status": 409, "category": "DUP", "field": "phone"},
        "DUP_PUBLIC_ID": {"code": "DUP_001_0004", "message": "You have already registered", "status": 409, "category": "DUP"},
        "DUP_SUBMISSION": {"code": "DUP_002_0001", "message": "You have already described this image", "status": 409, "category": "DUP"},
        "DUP_SURVEY_ROUND": {"code": "DUP_002_0002", "message": "You have already completed this survey round", "status": 409, "category": "DUP"},
        "DUP_PAYMENT_IMAGE": {"code": "DUP_003_0001", "message": "This screenshot has already been submitted", "status": 409, "category": "DUP"},
        "DUP_TRANSACTION": {"code": "DUP_003_0002", "message": "This transaction has already been used", "status": 409, "category": "DUP"},
        "DUP_IMAGE_OTHER_USER": {"code": "DUP_003_0003", "message": "This screenshot was already used by another user", "status": 409, "category": "DUP"},
        "DUPLICATE_SUBMISSION": {"code": "ERR_DUPLICATE_SUBMISSION", "message": "You have already submitted for this image.", "status": 409, "category": "DUP"},
        "SURVEY_EXISTS": {"code": "ERR_SURVEY_EXISTS", "message": "This survey round has already been submitted.", "status": 409, "category": "DUP"},
        "PARTICIPANT_EXISTS": {"code": "ERR_PARTICIPANT_EXISTS", "message": "Username, email, or phone is already registered.", "status": 409, "category": "DUP"},
        "AUTH_CONSENT_REQUIRED": {"code": "AUTH_001_0001", "message": "Please agree to the consent terms to continue", "status": 403, "category": "AUTH"},
        "AUTH_ACCOUNT_FLAGGED": {"code": "AUTH_001_0002", "message": "Your account has been flagged. Contact support.", "status": 403, "category": "AUTH"},
        "AUTH_ACCOUNT_DEACTIVATED": {"code": "AUTH_001_0003", "message": "Account has been deactivated", "status": 403, "category": "AUTH"},
        "AUTH_ACCESS_DENIED": {"code": "AUTH_002_0001", "message": "Access denied", "status": 403, "category": "AUTH"},
        "CONSENT_REQUIRED": {"code": "ERR_CONSENT_REQUIRED", "message": "Consent is required to continue.", "status": 403, "category": "AUTH"},
        "FLAGGED_ACCOUNT": {"code": "ERR_FLAGGED_ACCOUNT", "message": "Account flagged due to low attention scores.", "status": 403, "category": "AUTH"},
        "NF_PARTICIPANT": {"code": "NF_001_0001", "message": "Account not found. Please register first.", "status": 404, "category": "NF"},
        "NF_IMAGE": {"code": "NF_001_0002", "message": "Image not found", "status": 404, "category": "NF"},
        "NF_PAYMENT": {"code": "NF_001_0003", "message": "Payment not found", "status": 404, "category": "NF"},
        "NF_CONSENT": {"code": "NF_001_0004", "message": "Consent record not found", "status": 404, "category": "NF"},
        "NF_ROUTE_NOT_FOUND": {"code": "NF_001_0005", "message": "Route not found", "status": 404, "category": "NF"},
        "PARTICIPANT_NOT_FOUND": {"code": "ERR_PARTICIPANT_NOT_FOUND", "message": "Registration not found. Please complete registration first.", "status": 404, "category": "NF"},
        "NO_IMAGES": {"code": "ERR_NO_IMAGES", "message": "No images available.", "status": 404, "category": "NF"},
        "IMAGE_NOT_FOUND": {"code": "ERR_IMAGE_NOT_FOUND", "message": "Image not found.", "status": 404, "category": "NF"},
        "PAYMENT_NOT_FOUND": {"code": "ERR_PAYMENT_NOT_FOUND", "message": "Payment session not found.", "status": 404, "category": "NF"},
        "PAY_EXPIRED": {"code": "PAY_001_0001", "message": "Payment session expired. Please start a new payment.", "status": 410, "category": "PAY"},
        "PAY_INVALID_STATE": {"code": "PAY_001_0002", "message": "Payment cannot be processed in current state", "status": 400, "category": "PAY"},
        "PAY_INVALID_AMOUNT": {"code": "PAY_001_0003", "message": "Invalid payment amount", "status": 400, "category": "PAY"},
        "PAY_ALREADY_PROCESSED": {"code": "PAY_001_0004", "message": "Payment has already been processed", "status": 400, "category": "PAY"},
        "PAY_INVALID_IMAGE_TYPE": {"code": "PAY_001_0005", "message": "Invalid image format. Allowed: JPG, PNG, WEBP", "status": 400, "category": "PAY"},
        "PAY_INVALID_SHA256": {"code": "PAY_001_0006", "message": "Invalid file hash", "status": 400, "category": "PAY"},
        "PAY_VERIFY_ATTEMPTS_EXCEEDED": {"code": "PAY_001_0008", "message": "Maximum verification attempts reached. Please create a new payment session.", "status": 409, "category": "PAY"},
        "AUTH_INVALID_PAYMENT_TOKEN": {"code": "AUTH_002_0002", "message": "Invalid or expired payment authorization token.", "status": 403, "category": "AUTH"},
        "AUTH_EMAIL_OTP_INVALID": {"code": "AUTH_003_0001", "message": "Invalid verification code. Please try again.", "status": 403, "category": "AUTH"},
        "AUTH_EMAIL_OTP_EXPIRED": {"code": "AUTH_003_0002", "message": "Verification code expired. Request a new one.", "status": 410, "category": "AUTH"},
        "AUTH_EMAIL_OTP_TOO_MANY": {"code": "AUTH_003_0003", "message": "Too many attempts. Request a new verification code.", "status": 429, "category": "AUTH"},
        "AUTH_EMAIL_OTP_NOT_FOUND": {"code": "AUTH_003_0004", "message": "No verification code found. Please request a new one.", "status": 404, "category": "AUTH"},
        "AUTH_EMAIL_OTP_SEND_FAILED": {"code": "AUTH_003_0005", "message": "Email service is temporarily unavailable. Please try again in a minute.", "status": 503, "category": "AUTH"},
        "AUTH_EMAIL_OTP_SEND_TIMEOUT": {"code": "AUTH_003_0009", "message": "Email service took too long to respond. Please try again.", "status": 504, "category": "AUTH"},
        "AUTH_EMAIL_OTP_SEND_HTTP_ERROR": {"code": "AUTH_003_0010", "message": "Email service returned an error. Please try again.", "status": 503, "category": "AUTH"},
        "AUTH_EMAIL_MISMATCH": {"code": "AUTH_003_0006", "message": "Email does not match your registration details.", "status": 403, "category": "AUTH", "field": "email"},
        "AUTH_EMAIL_SAME": {"code": "AUTH_003_0007", "message": "Please enter a different email address to update.", "status": 400, "category": "AUTH", "field": "email"},
        "AUTH_EMAIL_NOT_VERIFIED": {"code": "AUTH_003_0008", "message": "Please verify your email before submitting.", "status": 403, "category": "AUTH"},
        "BOT_CHALLENGE_FAILED": {"code": "BOT_001_0001", "message": "Human verification failed. Please retry.", "status": 403, "category": "AUTH"},
        "PAYMENT_EXPIRED": {"code": "ERR_PAYMENT_EXPIRED", "message": "Payment session has expired. Please create a new payment.", "status": 410, "category": "PAY"},
        "PAYMENT_INVALID_STATE": {"code": "ERR_PAYMENT_INVALID_STATE", "message": "This payment has already been processed.", "status": 400, "category": "PAY"},
        "INVALID_AMOUNT": {"code": "ERR_INVALID_AMOUNT", "message": "Invalid payment amount.", "status": 400, "category": "PAY"},
        "INVALID_IMAGE_TYPE": {"code": "ERR_INVALID_IMAGE_TYPE", "message": "Invalid image format. Allowed: JPG, PNG, WEBP.", "status": 400, "category": "PAY"},
        "INVALID_SHA256": {"code": "ERR_INVALID_SHA256", "message": "Invalid file hash.", "status": 400, "category": "PAY"},
        "FRAUD_LOW_RESOLUTION": {"code": "FRAUD_001_0001", "message": "Screenshot is too blurry. Please upload a clearer image.", "status": 400, "category": "FRAUD"},
        "FRAUD_LOW_OCR_CONFIDENCE": {"code": "FRAUD_001_0002", "message": "Could not read the screenshot text. Please retake.", "status": 400, "category": "FRAUD"},
        "FRAUD_UNRECOGNIZED_APP": {"code": "FRAUD_001_0003", "message": "Please use Google Pay, Paytm, or BHIM", "status": 400, "category": "FRAUD"},
        "FRAUD_INVALID_BANKING_NAME": {"code": "FRAUD_001_0004", "message": "Payment not made to the correct beneficiary", "status": 400, "category": "FRAUD"},
        "FRAUD_INVALID_AMOUNT": {"code": "FRAUD_001_0005", "message": "Payment amount must be exactly ₹1", "status": 400, "category": "FRAUD"},
        "FRAUD_TIME_OUT_OF_RANGE": {"code": "FRAUD_001_0006", "message": "Payment time is outside the allowed payment-session window", "status": 400, "category": "FRAUD"},
        "FRAUD_INVALID_TIMESTAMP": {"code": "FRAUD_001_0007", "message": "Could not read payment time from screenshot", "status": 400, "category": "FRAUD"},
        "FRAUD_MISSING_TIMESTAMP": {"code": "FRAUD_001_0008", "message": "Payment time not found in screenshot", "status": 400, "category": "FRAUD"},
        "FRAUD_VPA_MISMATCH": {"code": "FRAUD_002_0001", "message": "Payment not made to correct UPI ID", "status": 400, "category": "FRAUD"},
        "FRAUD_NOTE_MISMATCH": {"code": "FRAUD_002_0002", "message": "Payment note does not match. Use the exact note shown.", "status": 400, "category": "FRAUD"},
        "FRAUD_AMOUNT_MISMATCH": {"code": "FRAUD_002_0003", "message": "Payment amount must be exactly ₹1", "status": 400, "category": "FRAUD"},
        "FRAUD_MISSING_SUCCESS": {"code": "FRAUD_002_0004", "message": "Payment success not detected in screenshot", "status": 400, "category": "FRAUD"},
        "FRAUD_FAILURE_INDICATOR": {"code": "FRAUD_002_0005", "message": "Payment appears to have failed. Check your UPI app.", "status": 400, "category": "FRAUD"},
        "FRAUD_DUPLICATE_IMAGE": {"code": "FRAUD_003_0001", "message": "This screenshot was already submitted by another user", "status": 409, "category": "FRAUD"},
        "FRAUD_DUPLICATE_IMAGE_SELF": {"code": "FRAUD_003_0004", "message": "You already submitted this screenshot. Please use a new payment screenshot.", "status": 409, "category": "FRAUD"},
        "FRAUD_REJECTED_REUSE": {"code": "FRAUD_003_0002", "message": "This screenshot was previously rejected", "status": 409, "category": "FRAUD"},
        "FRAUD_NOT_UPI_PAYMENT": {"code": "FRAUD_002_0008", "message": "Screenshot does not appear to be a UPI payment", "status": 400, "category": "FRAUD"},
        "FRAUD_MISSING_RECIPIENT": {"code": "FRAUD_002_0009", "message": "Payment recipient details not found in screenshot", "status": 400, "category": "FRAUD"},
        "PAYMENT_NOT_VERIFIED": {"code": "PAY_001_0007", "message": "Payment not verified. Please complete payment first.", "status": 403, "category": "PAY"},
        "DUPLICATE_IMAGE": {"code": "ERR_DUPLICATE_IMAGE", "message": "This screenshot has already been uploaded by another user.", "status": 409, "category": "FRAUD"},
        "DUPLICATE_IMAGE_SELF": {"code": "ERR_DUPLICATE_IMAGE_SELF", "message": "You already submitted this screenshot. Please use a new payment screenshot.", "status": 409, "category": "FRAUD"},
        "REJECTED_REUSE": {"code": "ERR_REJECTED_REUSE", "message": "This screenshot was previously rejected. Please use a fresh payment screenshot.", "status": 409, "category": "FRAUD"},
        "PAYMENT_REJECTED": {"code": "ERR_PAYMENT_REJECTED", "message": "Payment screenshot could not be verified.", "status": 400, "category": "FRAUD"},
    }

    aliases = {
        "DATABASE_ERROR": "SYS_DATABASE_ERROR",
        "INTERNAL_ERROR": "SYS_INTERNAL_ERROR",
        "MISSING_FIELDS": "VAL_MISSING_FIELDS",
        "INVALID_FORMAT": "VAL_INVALID_FORMAT",
        "INVALID_UUID": "VAL_INVALID_REQUEST_ID",
        "RATE_LIMIT": "RATE_LIMIT_EXCEEDED",
        "DESCRIPTION_LENGTH": "VAL_DESC_LENGTH",
        "FEEDBACK_LENGTH": "VAL_FEEDBACK_LENGTH",
        "RATING_INVALID": "VAL_RATING_INVALID",
        "WORD_COUNT": "VAL_WORD_COUNT",
        "DUPLICATE_SUBMISSION": "DUP_SUBMISSION",
        "SURVEY_EXISTS": "DUP_SURVEY_ROUND",
        "PARTICIPANT_EXISTS": "PARTICIPANT_EXISTS",
        "CONSENT_REQUIRED": "AUTH_CONSENT_REQUIRED",
        "FLAGGED_ACCOUNT": "AUTH_ACCOUNT_FLAGGED",
        "PARTICIPANT_NOT_FOUND": "NF_PARTICIPANT",
        "NO_IMAGES": "NF_IMAGE",
        "IMAGE_NOT_FOUND": "NF_IMAGE",
        "PAYMENT_NOT_FOUND": "NF_PAYMENT",
        "PAYMENT_EXPIRED": "PAY_EXPIRED",
        "PAYMENT_INVALID_STATE": "PAY_INVALID_STATE",
        "INVALID_AMOUNT": "PAY_INVALID_AMOUNT",
        "INVALID_IMAGE_TYPE": "PAY_INVALID_IMAGE_TYPE",
        "INVALID_SHA256": "PAY_INVALID_SHA256",
        "DUPLICATE_IMAGE": "FRAUD_DUPLICATE_IMAGE",
        "DUPLICATE_IMAGE_SELF": "FRAUD_DUPLICATE_IMAGE_SELF",
        "REJECTED_REUSE": "FRAUD_REJECTED_REUSE",
        "PAYMENT_REJECTED": "FRAUD_MISSING_SUCCESS",
    }
    for legacy_key, canonical_key in aliases.items():
        if canonical_key in error_codes:
            error_codes[legacy_key] = error_codes[canonical_key]
    return error_codes
