"""Shared backend audit/domain event constants."""

AUDIT_EVENT_PARTICIPANT_CREATED = "participant_created"
AUDIT_EVENT_SUBMISSION = "submission"
AUDIT_EVENT_PAYMENT_OCR_UNAVAILABLE = "payment_ocr_unavailable"
AUDIT_EVENT_PAYMENT_STATUS_TRANSITION = "payment_status_transition"
AUDIT_EVENT_PAYMENT_CREATE_SUCCESS = "payment_create_success"
AUDIT_EVENT_PAYMENT_CREATE_REUSED_ACTIVE = "payment_create_reused_active"
AUDIT_EVENT_PAYMENT_CREATE_FAILED = "payment_create_failed"
AUDIT_EVENT_PAYMENT_VERIFY_UPLOAD_STARTED = "payment_verify_upload_started"
AUDIT_EVENT_PAYMENT_VERIFY_UPLOAD_INVALID_STATE = "payment_verify_upload_invalid_state"
AUDIT_EVENT_PAYMENT_VERIFY_DUPLICATE_OTHER_USER = "payment_verify_duplicate_other_user"
AUDIT_EVENT_PAYMENT_VERIFY_REJECTED_REUSE = "payment_verify_rejected_reuse"
AUDIT_EVENT_PAYMENT_VERIFY_NEAR_DUPLICATE_OTHER_USER = "payment_verify_near_duplicate_other_user"

DOMAIN_EVENT_SUBMISSION_SAVED = "submission_saved"
DOMAIN_EVENT_PAYMENT_VERIFIED = "payment_verified"
DOMAIN_EVENT_PRIORITY_QUALIFIED = "priority_qualified"
DOMAIN_EVENT_REWARD_SELECTED = "reward_selected"

HTTP_METHOD_POST = "POST"
HTTP_METHOD_GET = "GET"
HTTP_METHOD_INTERNAL = "INTERNAL"
HTTP_REASON_ROUTE_NOT_FOUND = "route_not_found"
HTTP_REASON_METHOD_NOT_ALLOWED = "method_not_allowed"
PAYMENT_NOT_VERIFIED_REASON = "payment_not_verified"
