AUDIT_EVENT_PARTICIPANT_CREATED = "participant_created"
AUDIT_EVENT_CONSENT_RECORDED = "consent_recorded"
AUDIT_EVENT_SUBMISSION = "submission"

DOMAIN_EVENT_SUBMISSION_SAVED = "submission_saved"

HTTP_METHOD_GET = "GET"
HTTP_METHOD_POST = "POST"
HTTP_METHOD_INTERNAL = "INTERNAL"

HTTP_REASON_METHOD_NOT_ALLOWED = "method_not_allowed"
HTTP_REASON_ROUTE_NOT_FOUND = "route_not_found"
