"""Shared participant-domain constants."""

PARTICIPANT_STATUS_CREATED = "created"
PARTICIPANT_STATUS_EXISTS = "exists"
PARTICIPANT_STATUS_CONSENT_RECORDED = "consent recorded"

PARTICIPANT_STAGE_SURVEY = "survey"
PARTICIPANT_STAGE_FINISHED = "finished"
PARTICIPANT_FIELD_USERNAME = "username"
PARTICIPANT_FIELD_EMAIL = "email"
