"""Shared participant-domain constants."""

PARTICIPANT_STATUS_CREATED = "created"
PARTICIPANT_STATUS_EXISTS = "exists"
PARTICIPANT_STATUS_CONSENT_RECORDED = "consent recorded"

PARTICIPANT_PAYMENT_STATUS_PENDING = "pending"
PARTICIPANT_PAYMENT_STATUS_PAID = "paid"
PARTICIPANT_PAYMENT_STATUS_FAILED = "failed"
PARTICIPANT_PAYMENT_STATUS_REFUNDED = "refunded"
PARTICIPANT_PAYMENT_STATUS_CANCELLED = "cancelled"

PARTICIPANT_STAGE_PAYMENT = "payment"
PARTICIPANT_STAGE_SURVEY = "survey"
PARTICIPANT_STAGE_FINISHED = "finished"
PARTICIPANT_FIELD_USERNAME = "username"
PARTICIPANT_FIELD_EMAIL = "email"
