"""Shared payment-domain constants used across routes and services."""

PAYMENT_STATUS_PENDING = "pending"
PAYMENT_STATUS_PROCESSING = "processing"
PAYMENT_STATUS_SUCCESS = "success"
PAYMENT_STATUS_EXPIRED = "expired"
PAYMENT_STATUS_FAILED = "failed"
PAYMENT_STATUS_REJECTED_FRAUD = "rejected_fraud"
PAYMENT_STATUS_REFUNDED = "refunded"

PAYMENT_ACTIVE_STATUSES = (
    PAYMENT_STATUS_PENDING,
    PAYMENT_STATUS_PROCESSING,
)
PAYMENT_TERMINAL_STATUSES = (
    PAYMENT_STATUS_SUCCESS,
    PAYMENT_STATUS_EXPIRED,
    PAYMENT_STATUS_FAILED,
    PAYMENT_STATUS_REJECTED_FRAUD,
    PAYMENT_STATUS_REFUNDED,
)
PAYMENT_QR_BLOCKED_STATUSES = (
    PAYMENT_STATUS_EXPIRED,
    PAYMENT_STATUS_FAILED,
    PAYMENT_STATUS_REJECTED_FRAUD,
    PAYMENT_STATUS_REFUNDED,
)
PAYMENT_STATUS_READ_ALLOWED = (
    PAYMENT_STATUS_PENDING,
    PAYMENT_STATUS_PROCESSING,
    PAYMENT_STATUS_SUCCESS,
    PAYMENT_STATUS_EXPIRED,
    PAYMENT_STATUS_REJECTED_FRAUD,
    PAYMENT_STATUS_FAILED,
)

PAYMENT_DETECTED_APP_UNKNOWN = "unknown"

VERIFY_ATTEMPT_STATUS_STARTED = "started"
VERIFY_ATTEMPT_STATUS_SUCCESS = "success"
VERIFY_ATTEMPT_STATUS_REJECTED = "rejected"
VERIFY_ATTEMPT_STATUS_REJECTED_REUSE = "rejected"
VERIFY_ATTEMPT_STATUS_DUPLICATE = "duplicate"
VERIFY_ATTEMPT_STATUS_ERROR = "error"
VERIFY_ATTEMPT_STATUS_INVALID_STATE = "invalid_state"
VERIFY_ATTEMPT_STATUS_EXPIRED = "expired"

FRAUD_REASON_OCR_UNAVAILABLE = "ocr_unavailable"
FRAUD_REASON_MAX_ATTEMPTS_EXCEEDED = "max_attempts_exceeded"
FRAUD_REASON_DUPLICATE_HASH_SELF = "duplicate_hash_self"
FRAUD_REASON_DUPLICATE_HASH_OTHER = "duplicate_hash_other"
FRAUD_REASON_NEAR_DUPLICATE_SELF = "near_duplicate_self"
FRAUD_REASON_NEAR_DUPLICATE_OTHER = "near_duplicate_other"
FRAUD_REASON_REJECTED_REUSE = "rejected_reuse"
FRAUD_REASON_POLICY_RISK_THRESHOLD = "policy_risk_threshold"
FRAUD_REASON_VERIFICATION_FAILED = "verification_failed"
FRAUD_REASON_OCR_SIGNATURE_REPLAY_SELF = "ocr_signature_replay_self"
FRAUD_REASON_OCR_SIGNATURE_REPLAY_OTHER = "ocr_signature_replay_other"

VERIFY_DETAIL_KEY_OCR_CONFIDENCE = "ocr_confidence"
VERIFY_DETAIL_KEY_FAILURE_REASONS = "failure_reasons"
VERIFY_DETAIL_KEY_EXTRACTED_TEXT_LENGTH = "extracted_text_length"
VERIFY_DETAIL_KEY_UPLOADED_SHA256 = "uploaded_sha256"
VERIFY_DETAIL_KEY_RISK_SCORE = "risk_score"
VERIFY_DETAIL_KEY_DECISION_THRESHOLD = "decision_threshold"
VERIFY_DETAIL_KEY_OCR_SIGNATURE = "ocr_signature"
VERIFY_DETAIL_KEY_DISTANCE = "distance"
VERIFY_DETAIL_KEY_MAX_ATTEMPTS = "max_attempts"

PAYMENT_FILE_STAGE_PREFIX = "payments/staging"
PAYMENT_FILE_FINAL_PREFIX = "payments"
UPLOAD_SOURCE_FIELD_OBJECT_KEY = "upload_object_key"
UPLOAD_SOURCE_FIELD_IMAGE_BASE64 = "image_base64"
PAYMENT_VERIFICATION_ERROR = "verification_failed"
