"""Centralized payment verification reason-to-error mapping."""

from __future__ import annotations

from app.constants.ocr_constants import (
    FAILURE_FAILURE_INDICATOR,
    FAILURE_INVALID_AMOUNT,
    FAILURE_INVALID_DATETIME_BHIM,
    FAILURE_INVALID_DATETIME_GPAY,
    FAILURE_INVALID_DATETIME_PAYTM,
    FAILURE_MISSING_BHIM_LABEL,
    FAILURE_MISSING_PAID_BHIM,
    FAILURE_MISSING_PAYTM_LABEL,
    FAILURE_MISSING_SUCCESS,
    FAILURE_TIME_OUT_OF_RANGE,
    FAILURE_UNRECOGNIZED_APP,
)
from app.constants.payment_constants import (
    FRAUD_REASON_DUPLICATE_HASH_OTHER,
    FRAUD_REASON_DUPLICATE_HASH_SELF,
    FRAUD_REASON_MAX_ATTEMPTS_EXCEEDED,
    FRAUD_REASON_NEAR_DUPLICATE_OTHER,
    FRAUD_REASON_NEAR_DUPLICATE_SELF,
    FRAUD_REASON_OCR_SIGNATURE_REPLAY_OTHER,
    FRAUD_REASON_OCR_SIGNATURE_REPLAY_SELF,
    FRAUD_REASON_OCR_UNAVAILABLE,
    FRAUD_REASON_REJECTED_REUSE,
    FRAUD_REASON_VERIFICATION_FAILED,
)

PAYMENT_VERIFICATION_DEFAULT_ERROR_KEY = "SYS_PAYMENT_VERIFY_FAILED"

PAYMENT_VERIFICATION_REASON_ERROR_KEYS = {
    FAILURE_UNRECOGNIZED_APP: "FRAUD_UNRECOGNIZED_APP",
    FAILURE_MISSING_PAYTM_LABEL: "FRAUD_UNRECOGNIZED_APP",
    FAILURE_MISSING_BHIM_LABEL: "FRAUD_UNRECOGNIZED_APP",
    FAILURE_MISSING_PAID_BHIM: "FRAUD_UNRECOGNIZED_APP",
    FAILURE_INVALID_AMOUNT: "FRAUD_INVALID_AMOUNT",
    FAILURE_INVALID_DATETIME_GPAY: "FRAUD_INVALID_TIMESTAMP",
    FAILURE_INVALID_DATETIME_PAYTM: "FRAUD_INVALID_TIMESTAMP",
    FAILURE_INVALID_DATETIME_BHIM: "FRAUD_INVALID_TIMESTAMP",
    FAILURE_TIME_OUT_OF_RANGE: "FRAUD_TIME_OUT_OF_RANGE",
    FAILURE_MISSING_SUCCESS: "FRAUD_MISSING_SUCCESS",
    FAILURE_FAILURE_INDICATOR: "FRAUD_FAILURE_INDICATOR",
    FRAUD_REASON_MAX_ATTEMPTS_EXCEEDED: "PAY_VERIFY_ATTEMPTS_EXCEEDED",
    FRAUD_REASON_DUPLICATE_HASH_SELF: "FRAUD_DUPLICATE_IMAGE_SELF",
    FRAUD_REASON_DUPLICATE_HASH_OTHER: "FRAUD_DUPLICATE_IMAGE",
    FRAUD_REASON_NEAR_DUPLICATE_SELF: "FRAUD_DUPLICATE_IMAGE_SELF",
    FRAUD_REASON_NEAR_DUPLICATE_OTHER: "FRAUD_DUPLICATE_IMAGE",
    FRAUD_REASON_REJECTED_REUSE: "FRAUD_REJECTED_REUSE",
    FRAUD_REASON_OCR_SIGNATURE_REPLAY_SELF: "FRAUD_DUPLICATE_IMAGE_SELF",
    FRAUD_REASON_OCR_SIGNATURE_REPLAY_OTHER: "FRAUD_DUPLICATE_IMAGE",
    FRAUD_REASON_OCR_UNAVAILABLE: "SYS_PAYMENT_VERIFY_FAILED",
    FRAUD_REASON_VERIFICATION_FAILED: "SYS_PAYMENT_VERIFY_FAILED",
}

PAYMENT_VERIFICATION_REASON_PRIORITY = (
    FRAUD_REASON_DUPLICATE_HASH_SELF,
    FRAUD_REASON_DUPLICATE_HASH_OTHER,
    FRAUD_REASON_NEAR_DUPLICATE_SELF,
    FRAUD_REASON_NEAR_DUPLICATE_OTHER,
    FRAUD_REASON_REJECTED_REUSE,
    FRAUD_REASON_OCR_SIGNATURE_REPLAY_SELF,
    FRAUD_REASON_OCR_SIGNATURE_REPLAY_OTHER,
    FAILURE_UNRECOGNIZED_APP,
    FAILURE_MISSING_PAYTM_LABEL,
    FAILURE_MISSING_BHIM_LABEL,
    FAILURE_MISSING_PAID_BHIM,
    FAILURE_INVALID_AMOUNT,
    FAILURE_TIME_OUT_OF_RANGE,
    FAILURE_INVALID_DATETIME_GPAY,
    FAILURE_INVALID_DATETIME_PAYTM,
    FAILURE_INVALID_DATETIME_BHIM,
    FAILURE_FAILURE_INDICATOR,
    FAILURE_MISSING_SUCCESS,
    FRAUD_REASON_MAX_ATTEMPTS_EXCEEDED,
    FRAUD_REASON_OCR_UNAVAILABLE,
    FRAUD_REASON_VERIFICATION_FAILED,
)


def resolve_payment_verification_error_key(failure_reasons: list[str] | None) -> str:
    """Resolve a stable canonical error key for payment verification failures."""
    reasons = [reason for reason in (failure_reasons or []) if reason]
    if not reasons:
        return PAYMENT_VERIFICATION_DEFAULT_ERROR_KEY

    for reason in PAYMENT_VERIFICATION_REASON_PRIORITY:
        if reason in reasons:
            return PAYMENT_VERIFICATION_REASON_ERROR_KEYS.get(
                reason, PAYMENT_VERIFICATION_DEFAULT_ERROR_KEY
            )

    for reason in reasons:
        mapped = PAYMENT_VERIFICATION_REASON_ERROR_KEYS.get(reason)
        if mapped:
            return mapped

    return PAYMENT_VERIFICATION_DEFAULT_ERROR_KEY
