"""Shared backend route and endpoint constants."""

HEALTH_ROUTE = "/health"
ROOT_ROUTE = "/"
API_DOCS_ROUTE = "/api-docs"
API_DOCS_ENDPOINTS_ROUTE = "/api-docs/endpoints"
API_DOCS_ERRORS_ROUTE = "/api-docs/errors"
API_DOCS_EXAMPLES_ROUTE = "/api-docs/examples"

IMAGES_RANDOM_ROUTE = "/images/random"
PARTICIPANTS_ROUTE = "/participants"
CHECK_USERNAME_ROUTE = "/check-username"
CHECK_EMAIL_ROUTE = "/check-email"
CONSENT_ROUTE = "/consent"
PARTICIPANT_SESSION_ROUTE = "/participants/session"
PARTICIPANT_OPTIONS_ROUTE = "/participant-options"
EMAIL_OTP_REQUEST_ROUTE = "/email-otp/request"
EMAIL_OTP_VERIFY_ROUTE = "/email-otp/verify"
SUBMIT_ROUTE = "/submit"
CLIENT_ERROR_ROUTE = "/client-errors"
DOMAIN_EVENT_ENDPOINT = "domain_event"
