"""Shared backend route and endpoint constants."""

HEALTH_ROUTE = "/health"
ROOT_ROUTE = "/"
API_DOCS_ROUTE = "/api-docs"
API_DOCS_ENDPOINTS_ROUTE = "/api-docs/endpoints"
API_DOCS_ERRORS_ROUTE = "/api-docs/errors"
API_DOCS_EXAMPLES_ROUTE = "/api-docs/examples"

IMAGES_RANDOM_ROUTE = "/images/random"
PARTICIPANTS_ROUTE = "/participants"
CHECK_USERNAME_ROUTE = "/check-username"
CHECK_EMAIL_ROUTE = "/check-email"
CHECK_PHONE_ROUTE = "/check-phone"
CONSENT_ROUTE = "/consent"
PARTICIPANT_PAYMENT_STATUS_ROUTE = "/participants/<public_id>/payment-status"
PARTICIPANT_SESSION_ROUTE = "/participants/session"
PARTICIPANT_OPTIONS_ROUTE = "/participant-options"
SUBMIT_ROUTE = "/submit"
PAYMENTS_CREATE_ROUTE = "/payments/create"
PAYMENT_QR_ROUTE = "/payments/<payment_public_id>/qr"
PAYMENT_UPLOAD_URL_ROUTE = "/payments/<payment_public_id>/upload-url"
PAYMENT_VERIFY_UPLOAD_ROUTE = "/payments/<payment_public_id>/verify-upload"
PAYMENT_STATUS_ROUTE = "/payments/<payment_public_id>/status"
PAYMENT_TOKEN_ROUTE = "/payments/<payment_public_id>/token"
INTERNAL_PAYMENT_VERIFY_ROUTE = "/internal/payments/<payment_public_id>/verify"
CLIENT_ERROR_ROUTE = "/client-errors"

PAYMENT_VERIFY_UPLOAD_ENDPOINT_TEMPLATE = "/payments/{payment_public_id}/verify-upload"
DOMAIN_EVENT_ENDPOINT = "domain_event"
