"""Shared submission-domain constants."""

ATTENTION_FAILURE_MISSING_EXPECTED_KEYWORD = "missing_expected_keyword"
ATTENTION_FAILURE_TOO_SHORT = "attention_too_short"
ATTENTION_FAILURE_LOW_DISTINCT_WORD_COUNT = "low_distinct_word_count"
ATTENTION_FAILURE_COPIED_PATTERN = "copied_attention_pattern"
ATTENTION_FAILURE_TOO_FAST = "too_fast_attention"

PARTICIPANT_META_KEY_ATTENTION_MONITOR = "attention_monitor"
PARTICIPANT_META_KEY_RECENT_RESULTS = "recent_results"
PARTICIPANT_META_KEY_CONSECUTIVE_FAILURES = "consecutive_failures"
PARTICIPANT_META_KEY_RECENT_ATTENTION_SCORE = "recent_attention_score"
PARTICIPANT_META_KEY_LAST_CHECKED_AT = "last_checked_at"

SUBMISSION_META_KEY_ATTENTION = "attention"
SUBMISSION_META_KEY_STRICT = "strict"
SUBMISSION_META_KEY_EXPECTED_TERMS = "expected_terms"
SUBMISSION_META_KEY_MATCHED_TERMS = "matched_terms"
SUBMISSION_META_KEY_FAILURE_REASONS = "failure_reasons"
SUBMISSION_META_KEY_DISTINCT_WORD_COUNT = "distinct_word_count"
SUBMISSION_META_KEY_CONTENT_FINGERPRINT = "content_fingerprint"

SUBMISSION_RESPONSE_STATUS = "submitted"
