"""Shared submission-domain constants."""

ATTENTION_FAILURE_MISSING_EXPECTED_KEYWORD = "missing_expected_keyword"
ATTENTION_FAILURE_LOW_EXPECTED_TERM_RECALL = "low_expected_term_recall"
ATTENTION_FAILURE_TOO_SHORT = "attention_too_short"
ATTENTION_FAILURE_LOW_DISTINCT_WORD_COUNT = "low_distinct_word_count"
ATTENTION_FAILURE_LOW_DESCRIPTIVE_RICHNESS = "low_descriptive_richness"
ATTENTION_FAILURE_REPETITIVE_TEMPLATE = "repetitive_template_pattern"
ATTENTION_FAILURE_COPIED_PATTERN = "copied_attention_pattern"
ATTENTION_FAILURE_TOO_FAST = "too_fast_attention"
ATTENTION_FAILURE_LOW_RECALL = "low_alignment_recall"
ATTENTION_TIER_PASS = "pass"
ATTENTION_TIER_WEAK_PASS = "weak_pass"
ATTENTION_TIER_SUSPICIOUS = "suspicious"
ATTENTION_TIER_FAIL = "fail"

PARTICIPANT_META_KEY_ATTENTION_MONITOR = "attention_monitor"
PARTICIPANT_META_KEY_RECENT_ASSESSMENTS = "recent_assessments"
PARTICIPANT_META_KEY_RECENT_RESULTS = "recent_results"

SUBMISSION_META_KEY_ATTENTION = "attention"
SUBMISSION_META_KEY_STRICT = "strict"

SUBMISSION_RESPONSE_STATUS = "submitted"
